### ISSUE TITLE
CubeSQL date() function in WHERE clause 

### ISSUE THREAD

**Issue by zsvoboda** [cube-js/cube#3997]
Hi, I’m playing with the CubeSQL and Metabase. Everything works great except the Metabase Field Filters. Metabase generates the SQL below that works perfectly fine in MySQL but not in Cube:

```sql
select
    covidEventPersonAgePadded,
    infections
  from CovidEvent
  where date(`CovidEvent`.`covidEventDate`) BETWEEN ‘2021-12-29’ AND ‘2022-01-28’
  order by covidEventPersonAgePadded ASC
```

Internal: User(“Wrong type of argument (date), must be DateLiteral, actual: Function { name: ObjectName([Ident { value: \“date\“, quote_style: None }]), args: [Unnamed(CompoundIdentifier([Ident { value: \“CovidEvent\“, quote_style: Some(‘`’) }, Ident { value: \“covidEventDate\“, quote_style: Some(‘`’) }]))], over: None, distinct: false }“) 

Using the MySQL date() function in the select’s column list works just fine with Cube:

```sql
select
        date(`CovidEvent`.`covidEventDate`),
        covidEventPersonAgePadded,
        infections
    from CovidEvent
    order by covidEventPersonAgePadded ASC
returns expected result
```

**Comment by igorlukanin** [comment]
It looks like this issue is already resolved in the latest (v0.36.2) version of Cube with [query pushdown](https://cube.dev/docs/product/apis-integrations/sql-api#query-planning) turned on.

I've tried the following data model:
```yaml
  cubes:
    - name: CovidEvent
      sql: >
        SELECT '2021-12-01T00:00:00.000Z'::TIMESTAMP AS time, 123 AS value, 1 AS id UNION ALL
        SELECT '2022-01-01T00:00:00.000Z'::TIMESTAMP AS time, 123 AS value, 2 AS id UNION ALL
        SELECT '2022-02-01T00:00:00.000Z'::TIMESTAMP AS time, 123 AS value, 3 AS id

      dimensions:
        - name: id
          sql: id
          type: number
          primary_key: true
          public: true

        - name: covidEventPersonAgePadded
          sql: value
          type: number

        - name: infections
          sql: value
          type: number

        - name: covidEventDate
          sql: time
          type: time
```

This query worked after I adjusted the quotes:
```sql
select
    covidEventPersonAgePadded,
    infections,
    id
  from CovidEvent
  where date("CovidEvent"."covidEventDate") BETWEEN '2021-12-29' AND '2022-01-28'
  order by covidEventPersonAgePadded ASC;
```

Result:
<img width="670" alt="Screenshot 2024-09-25 at 16 56 06" src="https://github.com/user-attachments/assets/7f607587-b638-4971-93cd-27e32693d31f">

The second query worked as well (quotes adjusted):
```sql
select
        date("CovidEvent"."covidEventDate"),
        covidEventPersonAgePadded,
        infections
    from CovidEvent
    order by covidEventPersonAgePadded ASC;
```

Result:
<img width="615" alt="Screenshot 2024-09-25 at 16 57 29" src="https://github.com/user-attachments/assets/96a9f7af-bf8e-438b-aa09-c45c58118483">

So, closing this issue now.
