### ISSUE TITLE
Metrics defined via dbt integration fail due to capitalization

### ISSUE THREAD

**Issue by tacastillo** [cube-js/cube#4358]
**Describe the bug**

_Environment_
* on the Cube.js playground, hosted locally in a Docker container
* Snowflake
* dbt

When using metrics defined in dbt and imported into Cube.js, Cube ingests and maps dbt's metrics to Cube's format well. However, when trying to fetch a metric in Cube, the query receives an invalid identifier error because Cube uses quoted identifiers to resolve database entities.

Snowflake and other warehouses are finicky and the database objects are stored in _uppercase_. However, dbt is case **in**sensitive by default, and our best practice with clients is to have database objects defined in _lowercase_ in dbt.

**To Reproduce**
1. Spin up a Cube.js instance
2. Use Snowflake
3. Build a dbt project with objects named in lowercase. I haven't tested it yet, but I think the standard dbt [Jaffle Shop](https://github.com/dbt-labs/jaffle_shop) should fit the bill
4. Connect Cube.js to the right account and job ID in dbt Cloud to fetch the metric definitions.
5. Import them into the Cube.js playground
6. Go to the playground and fetch a dbt-generated metric using Cube
7. See error
8. Look at SQL and notice that identifiers are in quoted and in lowercase.

**Expected behavior**
Metrics should query the warehouse without failure.

**Screenshots**
Not a screenshot, but obfuscating a contrived example to show what happens.
```
/* Generated by Cube's dbt integration - Doesn't work */
SELECT
  column_name,
  count(*)
FROM
"database_name"."schema_name"."table_name" AS "table_name"
group by 1

/* Made in Cube.js - Works */
SELECT
  column_name,
  count(*)
FROM
  "SCHEMA_NAME"."TABLE_NAME" AS "t_a_b_l_e_name"
group by 1
```

**Minimally reproducible Cube Schema**
For the Cube schema, it's:
```
import dbt from '@cubejs-backend/dbt-schema-extension'

const dbtJobId = 424242;
const dbtApiKey = "<dbt-api-key>";

asyncModule(async () => {
  await dbt.loadMetricCubesFromDbtCloud(dbtJobId, dbtApiKey)
})
```

For dbt, it's:
```
version: 2

metrics:
  - name: total_sales
    label: Total Sales
    model: ref('sales')
    description: "The number of sales made"

    type: count
    sql: "1"

    timestamp: completed_at
    time_grains: [day, week, month]

    dimensions:
      - store
      - company

    filters:
      - field: sale_type
        operator: "in"
        value: "('list', 'of', 'possible', 'sales')"
```

Sample database hierarchy in the warehouse:
```
PRODUCTION
├─ SOURCES
├─ STAGING
├─ CORE
│  ├─ ITEMS
│  ├─ SALES
```

**Version:**
[e.g. 0.4.5]

**Additional context**
Moving this over from a question I asked in [Slack](https://cube-js.slack.com/archives/CC0403RRR/p1649049902740979).

I might be jumping the gun here, I'll acknowledge that and willingly accept anyone correcting me, but I believe when Cube's dbt integration kicks off, it parses the database entity straight from the `manifest.json` artifact, which would be in lowercase in our situation. Therefore the Cube.js schema is in lowercase, and the quoting identifiers persist that, but the query fails since the entities are technically in uppercase in the warehouse.

Thank you and hope y'all have a great day!
