### ISSUE TITLE
Issue Using FILTER PARAMS with SQL containing Boolean Operators ( IMP) 

### ISSUE THREAD

**Issue by nilansht** [cube-js/cube#5296]
The issue arises when we use filter params with a query which has boolean operators. It maps some kind of a strucutre for which filter params cannot be used in the cube.
For example
Using some cube with sql as

```
sql: ` PRINT '${FILTER_PARAMS.COACHING_CYCLE5.cycleEndTime.filter((data) => `${data}`)}'`,
  title: `Coaching Cycle5`,
```
with a query that is build using boolean operators
```
{
    "query": {
        "filters": [
            {
                "and": [
                    {
                        "or": [
                            {
                                "member": "COACHING_CYCLE5.cycleEndTime",
                                "operator": "inDateRange",
                                "values": [
                                    "2022-07-15", "2022-09-12"
                                ]
                            },
                            {
                                "member": "COACHING_CYCLE5.cycleEndTime",
                                "operator": "notSet"
                            }
                        ]
                    }
                ]
            }
        ],
        "dimensions": [
            "COACHING_CYCLE5.effectiveCycleLength"
        ],
        "measures": [
        ]
    }
}```

Now when you use ```cubejs-api/v1/sql``` API to check the sql , you see the parameters send to the cube are following an improper structure - where the cube sql always fails and get stuck..
```        "sql": [
            "SELECT\n      \"c_o_a_c_h_i_n_g__c_y_c_l_e5\".\"effectiveCycleLength\" \"c_o_a_c_h_i_n_g__c_y_c_l_e5__effective_cycle_length\"\n    FROM\n      ( PRINT '?') AS \"c_o_a_c_h_i_n_g__c_y_c_l_e5\"  WHERE (((\"c_o_a_c_h_i_n_g__c_y_c_l_e5\".\"CYCLE_END_TIME\" >= ?::timestamp_tz AND \"c_o_a_c_h_i_n_g__c_y_c_l_e5\".\"CYCLE_END_TIME\" <= ?::timestamp_tz) or (\"c_o_a_c_h_i_n_g__c_y_c_l_e5\".\"CYCLE_END_TIME\" IS NULL))) GROUP BY 1 ORDER BY 1 ASC LIMIT 10000",
            [
                [
                    [
                        "2022-07-15T00:00:00.000Z",
                        "2022-09-12T23:59:59.999Z"
                    ],
                    []
                ],
                "2022-07-15T00:00:00.000Z",
                "2022-09-12T23:59:59.999Z"
            ]
        ],`

This is where the issue is..
 [
                [
                    [
                        "2022-07-15T00:00:00.000Z",
                        "2022-09-12T23:59:59.999Z"
                    ],
                    []
                ],
```
this improper structure is not passed correctly in the sql statement which brings problems.

Expected should be direct usage of 2022-07-15T00:00:00.000Z as 0th element and 2022-09-12T23:59:59.999Z as 1th element to be used so that query works fine.

Version - Latest cube version

**Comment by nicolae-gorgias** [comment]
Yep, having same problem

**Comment by igorlukanin** [comment]
Hi @nilansht @nicolae-gorgias 👋 

I have checked the query above on Cube v0.36.7 (latest) with the following data model:

```yaml
cubes:
  - name: COACHING_CYCLE5
    sql: >
      SELECT 123 AS effectiveCycleLength '2025-01-01Z'::TIMESTAMPZ AS cycleEndTime
      WHERE {FILTER_PARAMS.COACHING_CYCLE5.cycleEndTime.filter(
        lambda x, y: f"""
          {x}, {y}
        """
      )}
      
    dimensions:
      - name: effectiveCycleLength
        sql: effectiveCycleLength
        type: number
      - name: cycleEndTime
        sql: cycleEndTime
        type: time
    dataSource: default
```

Here's the SQL that is being generated:

<img width="1392" alt="Screenshot 2024-10-09 at 02 14 28" src="https://github.com/user-attachments/assets/80077aff-221a-4b1b-921d-93ea778eca3b">

I feel like this looks correct now. So, closing this issue—please feel free to reopen!
