### ISSUE TITLE
ParserError("Expected ',' or ')' after column definition

### ISSUE THREAD

**Issue by kodeine** [cube-js/cube#5536]
Using prestodb with pre-aggregations i'm facing the following create table errors.

```
--
  CREATE TABLE dev_pre_aggregations.reports_campaign_table_rollup20211101_ftnidmh3_to3c30vu_1hlno0u AS SELECT
      "campaign".bidding_strategy "campaign__bidding_strategy", "campaign".campaignType "campaign__campaign_type", "campaign".createdAt "campaign__created_at", "campaign"._id "campaign__id", "campaign".servingStatus "campaign__serving_status", "campaign".state "campaign__state", "campaign".targetingType "campaign__targeting_type", "reports_campaign".accountId "reports_campaign__account_id", "reports_campaign".campaignId "reports_campaign__campaign_id", "reports_campaign".campaignName "reports_campaign__campaign_name", "reports_campaign".profileId "reports_campaign__profile_id", date_trunc('day', CAST(date_add('minute', timezone_minute("reports_campaign".reportDate AT TIME ZONE 'UTC'), date_add('hour', timezone_hour("reports_campaign".reportDate AT TIME ZONE 'UTC'), "reports_campaign".reportDate AT TIME ZONE 'UTC')) AS TIMESTAMP)) "reports_campaign__report_date_day", sum("reports_campaign".cost) "reports_campaign__ad_spend", sum("reports_campaign".clicks) "reports_campaign__clicks", sum("reports_campaign".attributedConversions14d) "reports_campaign__conversions", sum("reports_campaign".impressions) "reports_campaign__impressions", sum("reports_campaign".attributedUnitsOrdered14d) "reports_campaign__orders", sum("reports_campaign".attributedSales14d) "reports_campaign__sales"
    FROM
      REPORTS_CAMPAIGN AS "reports_campaign"
LEFT JOIN CAMPAIGNS AS "campaign" ON "reports_campaign".campaignId = "campaign".campaignId  WHERE ("reports_campaign".reportDate >= from_iso8601_timestamp('2021-11-01T00:00:00.000Z') AND "reports_campaign".reportDate <= from_iso8601_timestamp('2021-11-30T23:59:59.999Z')) GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
--
{
  "queryKey": [
    [
      "CREATE TABLE dev_pre_aggregations.reports_campaign_table_rollup20211101 AS SELECT\n      \"campaign\".bidding_strategy \"campaign__bidding_strategy\", \"campaign\".campaignType \"campaign__campaign_type\", \"campaign\".createdAt \"campaign__created_at\", \"campaign\"._id \"campaign__id\", \"campaign\".servingStatus \"campaign__serving_status\", \"campaign\".state \"campaign__state\", \"campaign\".targetingType \"campaign__targeting_type\", \"reports_campaign\".accountId \"reports_campaign__account_id\", \"reports_campaign\".campaignId \"reports_campaign__campaign_id\", \"reports_campaign\".campaignName \"reports_campaign__campaign_name\", \"reports_campaign\".profileId \"reports_campaign__profile_id\", date_trunc('day', CAST(date_add('minute', timezone_minute(\"reports_campaign\".reportDate AT TIME ZONE 'UTC'), date_add('hour', timezone_hour(\"reports_campaign\".reportDate AT TIME ZONE 'UTC'), \"reports_campaign\".reportDate AT TIME ZONE 'UTC')) AS TIMESTAMP)) \"reports_campaign__report_date_day\", sum(\"reports_campaign\".cost) \"reports_campaign__ad_spend\", sum(\"reports_campaign\".clicks) \"reports_campaign__clicks\", sum(\"reports_campaign\".attributedConversions14d) \"reports_campaign__conversions\", sum(\"reports_campaign\".impressions) \"reports_campaign__impressions\", sum(\"reports_campaign\".attributedUnitsOrdered14d) \"reports_campaign__orders\", sum(\"reports_campaign\".attributedSales14d) \"reports_campaign__sales\"\n    FROM\n      REPORTS_CAMPAIGN AS \"reports_campaign\"\nLEFT JOIN CAMPAIGNS AS \"campaign\" ON \"reports_campaign\".campaignId = \"campaign\".campaignId  WHERE (\"reports_campaign\".reportDate >= from_iso8601_timestamp(?) AND \"reports_campaign\".reportDate <= from_iso8601_timestamp(?)) GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12",
      [
        "2021-11-01T00:00:00.000Z",
        "2021-11-30T23:59:59.999Z"
      ],
      {}
    ],
    [
      {
        "indexName": "reports_campaign_table_rollup_campaign_index",
        "sql": [
          "CREATE INDEX reports_campaign_table_rollup_campaign_index ON dev_pre_aggregations.reports_campaign_table_rollup20211101 (`reports_campaign__profile_id`, `reports_campaign__account_id`, `reports_campaign__campaign_id`)",
          [],
          {}
        ]
      }
    ],
    [
      [
        {
          "refresh_key": "463045"
        }
      ]
    ]
  ],
  "targetTableName": "dev_pre_aggregations.reports_campaign_table_rollup20211101_ftnidmh3_to3c30vu_1hlno0u",
  "newVersionEntry": {
    "table_name": "dev_pre_aggregations.reports_campaign_table_rollup20211101",
    "structure_version": "to3c30vu",
    "content_version": "ftnidmh3",
    "last_updated_at": 1666965534783,
    "naming_version": 2
  },
  "buildRangeEnd": "2022-10-24T10:30:01.410"
} 
Error: Error during create table: CREATE TABLE dev_pre_aggregations.reports_campaign_table_rollup20211101_ftnidmh3_to3c30vu_1hlno0u (`campaign__bidding_strategy` varchar(255), `campaign__campaign_type` varchar(255), `campaign__created_at` timestamp(3), `campaign__id` varchar(255), `campaign__serving_status` varchar(255), `campaign__state` varchar(255), `campaign__targeting_type` varchar(255), `reports_campaign__account_id` varchar(255), `reports_campaign__campaign_id` double, `reports_campaign__campaign_name` varchar(255), `reports_campaign__profile_id` double, `reports_campaign__report_date_day` timestamp(3), `reports_campaign__ad_spend` bigint, `reports_campaign__clicks` bigint, `reports_campaign__conversions` bigint, `reports_campaign__impressions` bigint, `reports_campaign__orders` bigint, `reports_campaign__sales` bigint) WITH (build_range_end = '2022-10-24T10:30:01.410') INDEX reports_campaign_table_rollup_campaign_index_ftnidmh3_to3c30vu_1hlno0u ("reports_campaign__profile_id","reports_campaign__account_id","reports_campaign__campaign_id"): Internal: ParserError("Expected ',' or ')' after column definition, found: (")
    at WebSocket.<anonymous> (/cube/node_modules/@cubejs-backend/cubestore-driver/src/WebSocketConnection.ts:94:30)
    at WebSocket.emit (events.js:400:28)
    at Receiver.receiverOnMessage (/cube/node_modules/ws/lib/websocket.js:1008:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.dataMessage (/cube/node_modules/ws/lib/receiver.js:502:14)
    at Receiver.getData (/cube/node_modules/ws/lib/receiver.js:435:17)
    at Receiver.startLoop (/cube/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/cube/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at Socket.socketOnData (/cube/node_modules/ws/lib/websocket.js:1102:35)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
query SELECT table_name FROM information_schema.tables WHERE table_schema = ?
values [ 'dev_pre_aggregations' ]
Uploading external pre-aggregation error: 68da0705-e861-4f1a-99ec-c2873ec6ecd3-span-1 
--
```

**Comment by paveltiunov** [comment]
@kodeine Most likely, there's a mismatch between Cube and Cube Store versions.

**Comment by kodeine** [comment]
@paveltiunov i am using docker and on macbook pro m1 max.

```
version: '2.2'

networks:
  geo-network:
    name: geo-network
    driver: bridge

services:
  cube_api:
    restart: always
    image: cubejs/cube:latest
    networks:
      - geo-network
    ports:
      - 4100:4100
    environment:
      - CUBEJS_REFRESH_WORKER=false
    env_file: .env
    volumes:
      - .:/cube/conf
    depends_on:
      - cubestore_worker_1
      - cubestore_worker_2
      - cube_refresh_worker
      - redis

  cube_refresh_worker:
    restart: always
    image: cubejs/cube:latest
    networks:
      - geo-network
    environment:
      - CUBEJS_REFRESH_WORKER=true
    env_file: .env
    volumes:
      - .:/cube/conf

  cubestore_router:
    restart: always
    image: cubejs/cubestore:arm64v8
    networks:
      - geo-network
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_PORT=9999
      - CUBESTORE_SERVER_NAME=cubestore_router:9999
    volumes:
      - .cubestore/router:/cube/data

  cubestore_worker_1:
    restart: always
    image: cubejs/cubestore:arm64v8
    networks:
      - geo-network
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_SERVER_NAME=cubestore_worker_1:10001
      - CUBESTORE_WORKER_PORT=10001
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore/worker_1:/cube/data
    depends_on:
      - cubestore_router

  cubestore_worker_2:
    restart: always
    image: cubejs/cubestore:arm64v8
    networks:
      - geo-network
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_SERVER_NAME=cubestore_worker_2:10002
      - CUBESTORE_WORKER_PORT=10002
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore/worker_2:/cube/data
    depends_on:
      - cubestore_router

  redis:
    image: arm64v8/redis:alpine
    networks:
      - geo-network
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    logging:
      driver: none
```
