### ISSUE TITLE
No pre-aggregation partitions when set CUBEJS_DEV_MODE=false

### ISSUE THREAD

**Issue by karkill** [cube-js/cube#5913]
**Describe the bug**
I  turn off DevMode and get error when query. It works if set `CUBEJS_DEV_MODE`=`true`. I use `cube:v0.31.32` run on K8S
**Error**
```json
{
    "name": "StatusCodeError",
    "statusCode": 400,
    "message": "400 - {\"error\":\"Error: No pre-aggregation partitions were built yet for the pre-aggregation serving this query and this API instance wasn't set up to build pre-aggregations. Please make sure your refresh worker is configured correctly, running, pre-aggregation tables are built and all pre-aggregation refresh settings like timezone match. Expected table name patterns: prod_pre_aggregations.f_q_q_x_q_b__d_c_dc_rollup_*_dvpccnk_*\"}",
    "error": {
        "error": "Error: No pre-aggregation partitions were built yet for the pre-aggregation serving this query and this API instance wasn't set up to build pre-aggregations. Please make sure your refresh worker is configured correctly, running, pre-aggregation tables are built and all pre-aggregation refresh settings like timezone match. Expected table name patterns: prod_pre_aggregations.f_q_q_x_q_b__d_c_dc_rollup_*_dvpccnk_*"
    }
}
```

**refresh-worker** logs:
![image](https://user-images.githubusercontent.com/44264041/210518442-1df1b251-93a6-4c69-96d0-d86406aa103a.png)

**Version:**
cube:v0.31.32

**Comment by paveltiunov** [comment]
@karkill In production, you need a separate refresh worker instance. Please see https://cube.dev/docs/deployment/production-checklist#set-up-refresh-worker.

**Comment by karkill** [comment]
> @karkill In production, you need a separate refresh worker instance. Please see https://cube.dev/docs/deployment/production-checklist#set-up-refresh-worker.

![image](https://user-images.githubusercontent.com/44264041/211232958-fb40cb47-38ca-4d3c-b56d-59560dd7487a.png)
Hi @paveltiunov . I have a pod run `refresh worker`. This is my config.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: cube-refresh-worker
  name: cube-refresh-worker
  namespace: cube-js
spec:
  replicas: 1
  selector:
    matchLabels:
      service: cube-refresh-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: cube-refresh-worker
    spec:
      containers:
        - env: # Refer to https://cube.dev/docs/reference/environment-variables for more options
            - name: CUBEJS_API_SECRET
              value: "xxxxxxxxxxxx" # Old: <API_SECRET>
            - name: CUBEJS_CUBESTORE_HOST
              value: "cubestore-router" # USING THIS CUBESTORE HOST BECAUSE THE CUBESTORE ROUTER SERVICE IS NAMED "CUBESTORE-ROUTER"
            - name: CUBEJS_DB_HOST
              value: 'xxx.xx.xx.xx'
            - name: CUBEJS_DB_PORT
              value: 'xxxx'
            - name: CUBEJS_DB_NAME
              value: dssd
            - name: CUBEJS_DB_USER
              value: default
            - name: CUBEJS_DB_PASS
              value: dsadadadadas
            - name: CUBEJS_DB_TYPE
              value: clickhouse
            - name: CUBEJS_DB_SSL
              value: "true"
            - name: CUBEJS_DEV_MODE
              value: "true" # NEVER RUN DEV MODE IN K8S
            - name: CUBEJS_EXTERNAL_DEFAULT
              value: "true"
            - name: CUBEJS_REDIS_URL
              value: redis://redis:6379 # USING THIS REDIS URL BECAUSE THE REDIS SERVICE IS NAMED "REDIS"
            # SPECIFY THIS INSTANCE TO ACT AS A REFRESH WORKER
            - name: CUBEJS_REFRESH_WORKER
              value: "true"
          image: cubejs/cube:v0.31.32
          name: cube-refresh-worker
          resources:
            limits:
              cpu: "2000m"
              memory: "4096Mi"
            requests:
              cpu: "10m"
              memory: "32Mi"
          volumeMounts:
            - mountPath: /cube/conf
              name: cube-config
      restartPolicy: Always
      volumes:
        - name: cube-config
          persistentVolumeClaim:
            claimName: pvc-cube-config
```

**Comment by paveltiunov** [comment]
@karkill Please check that tables with a specified pattern from your error message `prod_pre_aggregations.f_q_q_x_q_b__d_c_dc_rollup_*_dvpccnk_*` are created in Cube Store: https://cube.dev/docs/caching/using-pre-aggregations/#inspecting-pre-aggregations.

**Comment by karkill** [comment]
> @karkill Please check that tables with a specified pattern from your error message `prod_pre_aggregations.f_q_q_x_q_b__d_c_dc_rollup_*_dvpccnk_*` are created in Cube Store: https://cube.dev/docs/caching/using-pre-aggregations/#inspecting-pre-aggregations.

Thanks for your help. 
I try to connect to cube-store but get some errors.
![image](https://user-images.githubusercontent.com/44264041/211510591-8a852356-baaa-4160-864d-9d3851ae311a.png)
My `cubestore-router.yaml`
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: cubestore-router
  name: cubestore-router
  namespace: ${ndms2_cube_stage_ns}
spec:
  serviceName: cubestore-router
  selector:
    matchLabels:
      service: cubestore-router
  template:
    metadata:
      labels:
        service: cubestore-router
    spec:
      containers:
        - env: # Refer to https://cube.dev/docs/reference/environment-variables for more options
            - name: CUBESTORE_META_PORT
              value: "9999"
            - name: CUBESTORE_DATA_DIR
              value: /cube/.cubestore/data
            - name: CUBESTORE_REMOTE_DIR
              value: /cube/data
            - name: CUBESTORE_SERVER_NAME
              value: cubestore-router:9999
            - name: CUBESTORE_WORKERS # Edit the workers if you change the number of worker replicas
              value: cubestore-workers-0.cubestore-workers:10000,cubestore-workers-1.cubestore-workers:10000,cubestore-workers-2.cubestore-workers:10000
          image: cubejs/cubestore:v0.31.32
          name: cubestore-router
          ports:
            - containerPort: 9999
          resources:
            limits:
              cpu: "2000m"
              memory: "4096Mi"
            requests:
              cpu: "10m"
              memory: "32Mi"
          volumeMounts:
            - mountPath: /cube/data
              name: cube-store
      restartPolicy: Always
      volumes:
        - name: cube-store
          persistentVolumeClaim:
            claimName: pvc-${ndms2_cube_stage_ns}-cube-store

```
