### ISSUE TITLE
Rollup Designer in Cube Core is broken for YAML data models

### ISSUE THREAD

**Issue by quy-ng** [cube-js/cube#5989]
Hi folks, 

I had a question which I posted at https://forum.cube.dev/t/syntax-error-missing-semicolon-in-schema/598 and slack, regarding syntax error.

My schema file is 
```yaml
cubes:
  - name: AnalystProfiles
    sql: SELECT * FROM analyst_profiles
      # preAggregations:
      # Pre-Aggregations definitions go here
      # Learn more here: https://cube.dev/docs/caching/pre-aggregations/getting-started
    joins: []
    measures:
      - name: count
        type: count
        drillMembers: [firstName, gender]
    dimensions:
      - name: age
        sql: age
        type: number
      - name: firstName
        sql: first_name
        type: string
      - name: gender
        sql: gender
        type: string
    dataSource: default
```

And error log is `Syntax error during 'AnalystProfiles.yaml' parsing: Missing semicolon. (2:8): - name: AnalystProfiles ^`

Basically, my schema file was generated by cube, but when I got an error that was confusing to me. I wonder if anyone here has ever encountered this?

FYI, I am using latest version with Docker

**Comment by jasonyanwenl** [comment]
I am facing the same issue even using the example yaml `orders.yml`. @dongchirua have you figured out this issue? Thank you!

**Comment by torshind** [comment]
This is the same for me. And this crashes cube as well:
```
cube_1           | Error: Cannot set headers after they are sent to the client
cube_1           |     at new NodeError (node:internal/errors:387:5)
cube_1           |     at ServerResponse.setHeader (node:_http_outgoing:644:11)
cube_1           |     at ServerResponse.header (/cube/node_modules/express/lib/response.js:771:10)
cube_1           |     at ServerResponse.send (/cube/node_modules/express/lib/response.js:170:12)
cube_1           |     at ServerResponse.json (/cube/node_modules/express/lib/response.js:267:15)
cube_1           |     at /cube/node_modules/@cubejs-backend/server-core/src/core/DevServer.ts:581:11
cube_1           |     at /cube/node_modules/@cubejs-backend/server-core/src/core/DevServer.ts:78:9
cube_1           | Error: Cannot set headers after they are sent to the client
cube_1           |     at new NodeError (node:internal/errors:387:5)
cube_1           |     at ServerResponse.setHeader (node:_http_outgoing:644:11)
cube_1           |     at ServerResponse.header (/cube/node_modules/express/lib/response.js:771:10)
cube_1           |     at ServerResponse.send (/cube/node_modules/express/lib/response.js:170:12)
cube_1           |     at ServerResponse.json (/cube/node_modules/express/lib/response.js:267:15)
cube_1           |     at /cube/node_modules/@cubejs-backend/server-core/src/core/DevServer.ts:82:25
```
My cube:
```
cubes:
  - name: c1_b1_raw_adult
    sql_table: c1.c1_b1_raw_adult
    data_source: default

    pre_aggregations:
      # Pre-aggregation definitions go here
      # Learn more here: https://cube.dev/docs/caching/pre-aggregations/getting-started

    joins: []

    measures:
      - name: count
        type: count

    dimensions:
      - name: age
        sql: age
        type: number
```
Proposed pre-aggregation:
```
name: main
measures:
  - c1_b1_raw_adult.count
dimensions:
  - c1_b1_raw_adult.age
```

Cube v0.33.2

**Comment by P-Arnold** [comment]
Hi, I'm also facing the same issue. Was anyone able to work it out?

**Comment by josephybh** [comment]
Any update?

**Comment by igorlukanin** [comment]
Hey @josephybh @P-Arnold and everyone 👋 

Which version of Cube are you using? Could you please try upgrading to the latest one?

I've checked this very source code with Cube v0.34 and it compiles and works perfectly for me:

```yml
cubes:
  - name: AnalystProfiles
    sql: SELECT * FROM analyst_profiles
      # preAggregations:
      # Pre-Aggregations definitions go here
      # Learn more here: https://cube.dev/docs/caching/pre-aggregations/getting-started
    joins: []
    measures:
      - name: count
        type: count
        drillMembers: [firstName, gender]
    dimensions:
      - name: age
        sql: age
        type: number
      - name: firstName
        sql: first_name
        type: string
      - name: gender
        sql: gender
        type: string
    dataSource: default
```

**Comment by GomesNayagam** [comment]
i use the same v0.34 it is not working either

**Comment by yb9255** [comment]
Hi guys, I also faced the same issue in v0.34.42 while I was following cube core tutorial. I even tried to use js format for data models, I still ran into parsing error because of `example.view_yml`.

**Comment by whtblktone** [comment]
Any update ?

**Comment by igorlukanin** [comment]
I was able to reproduce this on Cube Core v0.36.2. It looks like the Rollup designer there incorrectly detects data model file format. It initially suggests JavaScript even though my data model is in YAML:

<img width="1278" alt="Screenshot 2024-10-09 at 01 56 17" src="https://github.com/user-attachments/assets/10dde708-096c-4ca3-8800-2fb062c8ea44">

When I manually switched it to YAML and tried to add the rollup, the following error occurred:

<img width="1168" alt="Screenshot 2024-10-09 at 01 56 32" src="https://github.com/user-attachments/assets/4ff075ba-687c-4adc-b31c-d6ed9c9c3cf6">

However, when I try the same steps in Cube Cloud, it correctly detects data model file format and sets it to YAML automatically. Data model that I used:

```yaml
cubes:
  - name: AnalystProfiles
    sql: SELECT 123 AS age, 'John' AS first_name, 'male' AS gender
      # preAggregations:
      # Pre-Aggregations definitions go here
      # Learn more here: https://cube.dev/docs/caching/pre-aggregations/getting-started
    joins: []
    measures:
      - name: count
        type: count
        drillMembers: [firstName, gender]
    dimensions:
      - name: age
        sql: age
        type: number
      - name: firstName
        sql: first_name
        type: string
      - name: gender
        sql: gender
        type: string
    dataSource: default
```
