### ISSUE TITLE
Reusing measure definitions from two cubes to calculate a new measure

### ISSUE THREAD

**Issue by magnus-dahlback** [cube-js/cube#6200]
**Problem**

I have two cubes (RIDE and READY_VEHICLE) with one measure in each (RIDE.number_of_rides and READY_VEHICLE.total_ready_vehicles). Both cubes have common dimensions date, city and country.

I want to calculate a new measure "rides per vehicles" which is the ratio of number_of_rides / total_ready_vehicles available on these three dimensions. How do I do that while reusing measure definitions? I've been trying to use cube extension and data blending without success.

**Schema for READY_VEHICLE**
```YAML
cubes:
  - name: READY_VEHICLE
    sql: SELECT * FROM "VEHICLE"."DAILY_READY_VEHICLE"
    measures:
      - name: total_ready_vehicles
        type: count
        sql: vehicle_id
        description: Total number of ready vehicles
    dimensions:
      - name: date
        sql: date
        type: time
        description: The date
      - name: country
        sql: country
        type: string
        description: The country
      - name: city
        sql: city
        type: string
        description: The city
```

**Schema for RIDE**
```YAML
cubes:
  - name: RIDE
    sql: SELECT * FROM "CORE"."RIDE"
    measures:
      - name: number_of_rides
        type: count
        sql: "{CUBE}.\"RIDE_ID\""
        description: Total number of rides
    dimensions:
      - name: ride_id
        sql: ride_id
        type: string
        primary_key: true
        shown: false
        description: The unique identifier of a ride
      - name: city
        sql: "{CUBE}.\"CITY\""
        type: string
        description: The city where the ride was taken
      - name: country
        sql: "{CUBE}.\"COUNTRY\""
        type: string
        description: The country where the ride was taken
      - name: date
        sql: start_time_local
        type: time
        description: The start time of the ride in local time
```
