### ISSUE TITLE
SQL expressions in dimension definitions are not auto-wrapped in parentheses

### ISSUE THREAD

**Issue by igorlukanin** [cube-js/cube#6373]
From [Slack](https://cube-js.slack.com/archives/C04NYBJP7RQ/p1679951275112219):

Given the following sample schema:
```yml
cube:
  - name: items
    sql: SELECT * FROM items
    dimensions:
      - name: id
        sql: id
        type: number
        primaryKey: true
      - name: b
        sql: b
        type: boolean
      - name: c
        sql: c
        type: boolean
      - name: d
        sql: d
        type: boolean
      - name: a
        sql: "{CUBE.b} AND {CUBE.c} AND NOT {cube.d}"
        type: boolean
```
When I run the following query:
```sql
SELECT
	id,
	a
FROM
	items
WHERE
	a IS NULL
```
I expect output that looks something like the following(records where A is null):
```
id | a
---|---
 1 | 
 2 |
 3 |
 4 |
 5 |
```
However what I get is closer to the following:
```
id |  a
---|-----
 1 | TRUE
 2 | TRUE
 3 | TRUE
 4 | FALSE
 5 | TRUE
```
Why this arises becomes more clear after looking at the generated SQL:
```sql
SELECT
	id,
	b AND c AND NOT d
FROM
	items
WHERE
	b AND c AND NOT d IS NULL
```
This comes as a  in the SQL is replaced with b AND c AND NOT d  which creates b AND c AND NOT d IS NULL  which is not what I intended.
Having come from Looker what I expected/intended as for something like the following.
```sql
SELECT
	id,
	(b AND c AND NOT d)
FROM
	items
WHERE
	(b AND c AND NOT d) IS NULL
```

---

@paveltiunov thinks that "ideally Cube should handle this."

**Comment by Wardormeur** [comment]
I have another scenario where a comparison is used resulting in the following error:
`Arrow error: Compute error: Error: Syntax error: Unexpected keyword IS at`
The culprite is the same, in a different scenario:
```yml
    name: my_date
    sql: CAST({CUBE}.reference_date AS TIMESTAMP) <= CURRENT_TIMESTAMP
    type: boolean
```
When being cast as a boolean, it append `IS TRUE` at the end. This result in `CURRENT_TIMESTAMP IS TRUE` which is invalid
`... CASE WHEN (CAST('my_table'.reference_date AS TIMESTAMP) <= CURRENT_TIMESTAMP IS TRUE`

To fix it, you have to add explicit parentheses around the whole comparison
Such as 
```yml
    name: my_date
    sql: (CAST({CUBE}.reference_date AS TIMESTAMP) <= CURRENT_TIMESTAMP)
    type: boolean
```
I would agree that the point of the tool is to make it less painful to write SQL, this requires us to debug the query for what should be a classic scenario
Cheers

**Comment by samjewell** [comment]
You could assign this to me if you like, I wouldn't mind taking a crack at it.

I also just hit this issue, working with the BigQuery data source. Adding my repro as an extra test case, since it's a *loud* variant of this bug (a syntax error, rather than the silently-wrong results in the original report):

```yml
dimensions:
  - name: is_pipeline
    sql: "{CUBE}.stage_number BETWEEN 2 AND 6 AND {CUBE}.element_source != 'Non-Contracting Opportunities'"
    type: boolean
```

Filtering on that dimension:

```json
{ "filters": [{ "member": "orders.is_pipeline", "operator": "equals", "values": ["true"] }] }
```

renders as (`BigqueryQuery`'s `castParameter` supplying the cast):

```sql
WHERE ... AND orders.element_source != 'Non-Contracting Opportunities' = CAST(? AS BOOL)
```

which BigQuery rejects as a chained comparison: `Syntax error: Unexpected "="`.

Note that even a single-comparison boolean dimension (`sql: "{CUBE}.stage_number = 7"`) breaks the same way - `stage_number = 7 = CAST(? AS BOOL)`.

So across the reports on this issue there are three symptoms from the one root cause, which might make a decent test matrix for the fix:

1. `IS NULL` on a compound boolean dimension - silently wrong results (original report)
2. `IS TRUE` appended to a comparison expression - syntax error on Arrow/DuckDB (comment above)
3. `= CAST(? AS BOOL)` appended to a comparison expression - syntax error on BigQuery (this comment)

The workaround for all three is wrapping the dimension SQL in parentheses by hand.
