### ISSUE TITLE
How to correctly define pre-aggregations for views?

### ISSUE THREAD

**Issue by skervim** [cube-js/cube#6464]
Given a view `MyView` and a Cube `MyCube`.

Using Superset with Cube Cloud, a query of the following kind is sent to Cube Cloud:

```javascript
{ 
  "measures": [ 
    "MyView.some_measure" 
  ], 
  "dimensions": [ 
    "MyView.some_dimension" 
  ], 
 (...)
```
but the defined pre-aggregation is not triggered. 

If I slightly change the query however, replacing the view-prefix with the cube-prefix that is included in `MyView`:
```javascript
{ 
  "measures": [ 
    "MyCube.some_measure" 
  ], 
  "dimensions": [ 
    "MyCube.some_dimension" 
  ], 
 (...)
```
the pre-aggregation is successfully triggered. 

The only thing I find in the docs at [Views | Cube Docs](https://cube.dev/docs/schema/reference/view) is: 

> Views also do not define any pre-aggregations, instead they re-use pre-aggregations defined by the underlying cubes.

How can I make Cube detect the pre-aggregation for the query with the view name in it?

**Comment by paveltiunov** [comment]
@skervim Pre-aggregations should be defined on a cube level. Views will use them. It might be helpful to provide your data model files here.

**Comment by TobiasMaehl-pIX** [comment]
@paveltiunov We have the same issue. I was able to isolate that cube is properly resolving the measure names to match pre aggregations defined on cube level, but not dimensions (incl. time dimensions).
This can also be seen in the rollup designer in the Playground. For measures, the suggested rollup shows the correct cube name. But for dimensions, it suggests the view.

**Query:**
```javascript
{
  measures: [
    'view.count'
  ],
  timeDimensions: [
    {
      dimension: 'view.date',
      granularity: 'month'
    }
  ]
}
```  

**Suggested rollup definition:**
```javascript
main: {
  measures: [
    cube.count
  ],
  timeDimension: view.date,
  granularity: `month`
}
```
It should use the cube.date.

**Comment by TobiasMaehl-pIX** [comment]
@igorlukanin Could you please get in touch with the team to have a look at this? This currently prevents us from using views as the pre-aggregations don't work for them.

**Comment by igorlukanin** [comment]
Hey @TobiasMaehl-pIX 👋 

Here's a data model file that I quickly jotted down:

```yml
cubes:
  - name: abc_cube
    sql: >
      SELECT
        123 AS foo,
        '2023-09-01T12:00:00.000Z' AS time

    measures:
      - name: count
        type: count

    dimensions:
      - name: time
        sql: time
        type: time

    pre_aggregations:
      - name: main
        measures:
          - count
        time_dimension: time
        granularity: month
        
views:
  - name: abc_view

    cubes:
      - join_path: abc_cube
        includes: "*"
```

Also, here's the query that I run:
```json
{ 
  "timeDimensions": [ 
    { 
      "dimension": "abc_cube.time", 
      "granularity": "month" 
    } 
  ], 
  "measures": [ 
    "abc_cube.count" 
  ] 
} 
```

I can confirm that this data model works for me:
<img width="1818" alt="Screenshot 2023-09-01 at 20 33 49" src="https://github.com/cube-js/cube/assets/3852894/13194264-2ac9-469c-b47e-2c30e6841249">
<img width="1818" alt="Screenshot 2023-09-01 at 20 33 52" src="https://github.com/cube-js/cube/assets/3852894/0aba6545-9410-4892-a5f0-caa7befbfbd3">
