### ISSUE TITLE
Got "Cube 'Orders' not found for path 'Orders.count'" when trying the GraphQL API in the getting started project

### ISSUE THREAD

**Issue by jasonyanwenl** [cube-js/cube#6497]
**Describe the bug**
When following this [doc](https://cube.dev/docs/getting-started/core/query-data) to query the example cube `orders` using the below GraphQL request:
```
query CubeQuery  { 
  cube(limit: 50) {
    orders(orderBy: {count: desc } ) {
      count
      status
    }
  }
}
```

I get the below errors:
```
{
  "errors": [
    {
      "message": "Cube 'Orders' not found for path 'Orders.count'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "cube"
      ]
    }
  ],
  "data": null
}
```

**To Reproduce**
1. Followed the [step1](https://cube.dev/docs/getting-started/core/create-a-project) and created a demo Cube service in Docker.
2. Open in my web browser localhost:4000 with the example database `demo-db.cube.dev`
3. Followed the [step2](https://cube.dev/docs/getting-started/core/query-data) and generated a schema `cubes/orders.yml` for the table `public.orders`.
4. Go to the `Playground`, click the `GraphQL`, then click the play button and saw the error as in the below screenshot.

**Expected behavior**
I expect to see the actual queried metric data.

**Screenshots**
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/34975811/234441871-8aacda7e-4f38-47e7-bad1-aa7f0f6e2292.png">

**Minimally reproducible Cube Schema**
In case your bug report is data modeling related please put your minimally reproducible Cube Schema here.
You can use selects without tables in order to achieve that as follows.

```yaml
cubes:
  - name: orders
    sql_table: public.orders
    pre_aggregations:
      # Pre-Aggregations definitions go here
      # Learn more here: https://cube.dev/docs/caching/pre-aggregations/getting-started
    joins: []
    measures:
      - name: count
        type: count
      - name: number
        sql: number
        type: sum
    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true
      - name: status
        sql: status
        type: string
      - name: created_at
        sql: created_at
        type: time
      - name: completed_at
        sql: completed_at
        type: time
    data_source: default
```

**Version:**
Not sure. Please let me know how I can find it. I just follow the getting started guide to pull the latest docker image:

```
% docker ps -a
CONTAINER ID   IMAGE                COMMAND                  CREATED        STATUS        PORTS                                              NAMES
cc7b014054f6   cubejs/cube:latest   "docker-entrypoint.s…"   19 hours ago   Up 18 hours   0.0.0.0:4000->4000/tcp, 0.0.0.0:15432->15432/tcp   my-first-cube-project-cube-1

% docker images
REPOSITORY                                                                                             TAG          IMAGE ID       CREATED         SIZE
cubejs/cube                                                                                            latest       fa676c498537   6 days ago      811MB
...
```

**Comment by jasonyanwenl** [comment]
Somehow I found that if I capitalized the `orders` in orders.yml as shown below:
```yaml
cubes:
  - name: Orders  # Capitalized
    sql_table: public.orders
...
```
The GraphQL can return right metric data w/o any further modification. I don't know why though.

In addition, after capitalizing `Orders`, the `chart` button will fail:
<img width="1764" alt="image" src="https://user-images.githubusercontent.com/34975811/234470955-2f7e4f2d-375d-42ea-8fe1-793d9820d5e6.png">
