### ISSUE TITLE
Pre-aggregation : CUBE.name is not allowed

### ISSUE THREAD

**Issue by mir1198yusuf** [cube-js/cube#6593]
My Cube definition is as follows: 
```
cubes:
  - name: countries
    data_source: default
    sql_table: countries
    dimensions:
      - name: id
        sql: id
        type: number
      - name: name
        sql: name
        type: string
    pre_aggregations:
      - name: abcj
        type: original_sql
        dimensions:
          - CUBE.name
```

But getting below error in playground

![image](https://github.com/cube-js/cube/assets/34382235/567f9091-9377-473d-bb12-9b3be99648a8)

Please help!
Thanks in advance.
