### ISSUE TITLE
Parameters cannot be used with normal Statement objects, use PreparedStatements instead

### ISSUE THREAD

**Issue by zhjuncai** [cube-js/cube#6627]
**Describe the bug**
Got error "Parameters cannot be used with normal Statement objects, use PreparedStatements instead" when build pre-aggregations on latest cube version 1.33.8

**Expected behavior**

**Screenshots**
```
Error: [Databricks][JDBC](11220) Parameters cannot be used with normal Statement objects, use PreparedStatements instead.
    at DatabricksDriver.queryPromised (/jdbc-driver/src/JDBCDriver.ts:253:15)
    at DatabricksDriver.queryColumnTypes (@cubejs-backend/databricks-jdbc-driver/src/DatabricksDriver.ts:517:22)
    at PreAggregationLoader.getTableDataWithoutTempTable (@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:1289:25)
    at PreAggregationLoader.downloadExternalPreAggregation (/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:1203:21)
    at PreAggregationLoader.runWriteStrategy (@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:1026:25)
    at Object.query (/Users/~/git/BNA/bi-cube-services/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryCache.ts:592:26)
    at QueryQueue.processQuery (/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:750:25)
Error while querying: scheduler-c80c8956-55dc-4b5b-a034-4ff65698e3c0 (3615ms)
```

**Minimally reproducible Cube Schema**

use partition_granularity which will have ? in the statement

```yml
cubes:
  - name: orders
    sql: >
      SELECT * FROM orders
        
    public: false

    pre_aggregations:
      - name: count_per_day
        measures:
          - count
        dimensions:
          - CUBE.supplier_anid
        time_dimension: CUBE.created_date
        granularity: day
        partition_granularity: month
        refresh_key:
          every: 5 minutes
        indexes:
          supplier_anid_index:
            columns:
              - CUBE.supplier_anid
        build_range_start:
          sql: SELECT DATE((year(now()) - 3) || '-01-01')
        build_range_end:
          sql: SELECT DATE((year(now())) || '-12-31')

    dimensions:
      - name: id
        sql: PO_ID
        type: number
        primary_key: true

      ...

    measures:
      - name: count
        type: count
        title: Order count

    dataSource: default

```

**Version:**
0.33.8

**Additional context**
```
protected async queryPromised(query: string, cancelObj: any, options: any) {
    options = options || {};
    try {
      const conn = await this.pool.acquire();
      try {
        const prepareConnectionQueries = options.prepareConnectionQueries || [];
        for (let i = 0; i < prepareConnectionQueries.length; i++) {
          await this.executeStatement(conn, prepareConnectionQueries[i]);
        }
        return await this.executeStatement(conn, query, cancelObj);
      } finally {
        await this.pool.release(conn);
      }
    } catch (ex: any) {
      if (ex.cause) {
        throw new Error(ex.cause.getMessageSync());
      } else {
        throw ex;
      }
    }
  }
```

is it only support Statement?
