### ISSUE TITLE
Add `fortnight` granularity

### ISSUE THREAD

**Issue by nolde** [cube-js/cube#6643]
**Is your feature request related to a problem? Please describe.**
We have `week` and `month` as granularity, but no `fortnight`. Would be nice to not need extra transformation to handle fortnight periods.

**Describe the solution you'd like**
Add support for `fortnight` granularity.

**Describe alternatives you've considered**
Use `week` granularity, merge consecutive weeks.

**Comment by paveltiunov** [comment]
#177

**Comment by igorlukanin** [comment]
Hi @nolde 👋 

This is finally supported with https://github.com/cube-js/cube/issues/8488

Data model example:
```yaml
    # ...

    dimensions:
      - name: timestamp
        sql: timestamp
        type: time

        granularities:
          - name: fortnight
            interval: 2 weeks
            origin: "2024-10-01"
```
