### ISSUE TITLE
Include: * Not Working in Views

### ISSUE THREAD

**Issue by giftcash-dakota** [cube-js/cube#6660]
**Description:**
When trying to use `include: *` in a view(to use the include/except pattern), it gives the error message: `YAMLException: name of an alias node must contain at least one character (24:20)`.

**Reproduction Steps:**
Steps to reproduce the behaviour:
1. Create yaml schema file with the code from the schema below.
2. Observe the console output to see the error.

**Expected behaviour:**
I expect that when I use that pattern, I will be able to include all dimensions/measures from a cube and selectively exclude dimensions/measures using the `excludes` parameter.

**Minimally reproducible Cube Schema:**
```yml
cubes:
  - name: ExcludeTestCube
    sql: >
      SELECT 1 AS id, 100 AS amount, 'new' AS status

    dimensions:
      - name: id
        sql: id
        type: number

views:
  - name: ExcludeTestView

    cubes:
      - join_path: ExcludeTestCube
        includes: *
        excludes:
          - id
```

**Version:**
0.33.5

**Comment by keydunov** [comment]
Hi @giftcash-dakota!

Thank you for reporting this. I can confirm this is the existing issue, and we are fixing it now. As a workaround you can use double quotes.

```
cubes:
  - name: ExcludeTestCube
    sql: >
      SELECT 1 AS id, 100 AS amount, 'new' AS status

    dimensions:
      - name: id
        sql: id
        type: number

views:
  - name: ExcludeTestView

    cubes:
      - join_path: ExcludeTestCube
        includes: "*"
        excludes:
          - id
```
