### ISSUE TITLE
Snowflake Driver - Pre-aggregations containing nullable decimal measures fail to build using Export Bucket

### ISSUE THREAD

**Issue by ferreiramx** [cube-js/cube#6693]
**Describe the bug**
Pre-aggregations containing a decimal-type measure that may contain null values due to filters in the measure's definition fail to build when using an Export Bucket; whereas using the regular streaming strategy builds them correctly.

**To Reproduce**

1. Create a dummy table in Snowflake, with a column containing an integer and the other a decimal:
```sql
create or replace TABLE CUBE.DUMMY (
	ITEM_ID NUMBER(38,0),
	ITEM_TYPE VARCHAR(16777216),
	PRICE_INT NUMBER(38,0),
        PRICE_DECIMAL NUMBER(38,2)
);
INSERT INTO CUBE.DUMMY VALUES (1,'A',10,10.0), (2,'B',20,20.0);
```

2. Create a dummy Cube schema defining a pre-aggregation based on the `price_int` column, and one on the `price_decimal` column. Define a filter on the measures so that `item_type` "B" produces a NULL on the aggregation:

```yaml
cubes:
  - name: Dummy

    sql: SELECT * FROM "CUBE"."DUMMY"

    preAggregations:
      - name: dummy_agg_int
        dimensions:
          [
            CUBE.item_id,
            CUBE.item_type
          ]
        measures:
          [
            CUBE.price_int
          ]
        type: rollup

      - name: dummy_agg_dec
        dimensions:
          [
            CUBE.item_id,
            CUBE.item_type
          ]
        measures:
          [
            CUBE.price_decimal
          ]
        type: rollup

    measures:
      - name: price_int
        type: sum
        sql: "{CUBE}.price_int"
        format: currency
        filters:
          - sql: "{CUBE}.item_type = 'A'"
      
      - name: price_decimal
        type: sum
        sql: "{CUBE}.price_decimal"
        format: currency
        filters:
          - sql: "{CUBE}.item_type = 'A'"

    dimensions:
      - name: item_id
        sql: "{CUBE}.item_id"
        type: number
        primary_key: true
        shown: true

      - name: item_type
        sql: "{CUBE}.item_type"
        type: string

    dataSource: default
```
3. Run Cube without an export bucket configured. Both pre-aggregations build successfully. When queried, we get the expected result:
```json
"data": [
   {
      "Dummy.item_type": "A",
      "Dummy.price_int": "10"
   },
   {
      "Dummy.item_type": "B",
      "Dummy.price_int": null
   }
]
```
and

```json
"data": [
   {
      "Dummy.item_type": "A",
      "Dummy.price_decimal": "10"
   },
   {
      "Dummy.item_type": "B",
      "Dummy.price_decimal": null
   }
]
```

5. Clear cubestore
6. Run Cube with an export bucket configured. `dummy_agg_int` will build correctly, while `dummy_agg_dec` will fail to build with the following error:
```json
"status": "failure: Error during create table: CREATE TABLE CUBE_PREAGG.dummy_dummy_agg_dec_oujvswm2_0gy2mu4o_1i7vo0o (`dummy__item_id` int, `dummy__item_type` varchar(255), `dummy__price_decimal` decimal) WITH (input_format = 'csv_no_header') LOCATION ?: Create table failed: Can't parse '\\\\N' column value for 'dummy__price_decimal' column: Internal: invalid digit found in string"
```

**Expected behavior**
Both pre-aggregations should build and produce the same result regardless of if an export bucket is used or not.

**Version:**
Latest, 0.33.24 as of writing this.

**Additional context**
Looking at the driver code, I believe that perhaps decimal values are not being handled consistently when using the `unload` vs the `stream` methods of the Snowflake driver. Integer-type measures behave consistently with both strategies and correctly handle null values.
