### ISSUE TITLE
setting `CUBEJS_PRE_AGGREGATIONS_BUILDER` to true in production does not build pre aggregations

### ISSUE THREAD

**Issue by moafak** [cube-js/cube#6706]
**Problem**

Setting `CUBEJS_PRE_AGGREGATIONS_BUILDER` to `true` does not build pre aggregations unless dev mode is enabled.

**Related Cube.js schema**
```javascript
cube(`Cube`, {
  sql: `` //, ...
  pre_aggregations: {
            //  ...
            external: false
        }
    }
})
```

Does not build pre-aggregations :arrow_down: 
```yaml
CUBEJS_DEV_MODE: false
CUBEJS_PRE_AGGREGATIONS_BUILDER: true
CUBEJS_PRE_AGGREGATIONS_SCHEMA: public
```

Docs do not mention that this setting does not work in production mode.
https://cube.dev/docs/reference/environment-variables#cubejs-pre-aggregations-builder
