### ISSUE TITLE
COMPILE_CONTEXT.security_context is not working correctly with public

### ISSUE THREAD

**Issue by jayctran** [cube-js/cube#6710]
**Describe the bug**
I am trying to set up access control where it's utilising COMPILE_CONTEXT as shown in the recipes for access control.
However, when I specify:

name: <cube name>
public: COMPILE_CONTEXT.security_context.isAdmin 

The model always shows up when I hit the /meta api - in devMode pubic is always true.

Cube configuration looks like this:

```javascript
module.exports = {
  contextToAppId: ({ securityContext }) => {
    return 'CUBEJS_APP_${securityContext.preferred_username}';
  },
  extendContext: ({ securityContext }) => {
    var groups;
    try {
      groups = securityContext.groups;
    } catch {
      groups = null;
    }

    if (groups === undefined || groups === null ) {
      throw new Error('Groups in SecurityContext is undefined or null');
    }
    else if (groups.length === 0) {
      throw new Error('Group values not found in SecurityContext');
    }

    console.info(typeof groups);
    console.info(JSON.stringify(groups));
    console.info(groups.includes("cube-admin"))
    return {
      isAdmin: groups.includes("cube-admin")
    };
  },
};
```

Log of above when hitting the /meta api:

> object
> ["cube-public"]
> false

**To Reproduce**
1. Follow steps in https://cube.dev/docs/recipes/controlling-access-to-cubes-and-views
2. Hit /meta api
3. See cube/view that uses COMPILE_CONTEXT has public: true

**Expected behavior**
Expecting to see public: false where isAdmin: false

**Screenshots**
Schema:
![image](https://github.com/cube-js/cube/assets/28096214/cd01b3f6-95df-4196-a0ee-a2d9f591bc65)

Meta Output:
![image](https://github.com/cube-js/cube/assets/28096214/7a76ce6d-23cd-4bfa-ba65-e36ccfa7abf0)

**Minimally reproducible Cube Schema**
In case your bug report is data modelling related please put your minimally reproducible Cube Schema here.
You can use selects without tables in order to achieve that as follows.

```yaml
views:
  - name: vw_adf_load_config
    public: COMPILE_CONTEXT.security_context.isAdmin
    includes:
      - adf_load_config.source_conn_code
      - adf_load_config.source_table_schema
      - adf_load_config.source_table_name
```

**Version:**
0.33.25
