### ISSUE TITLE
Joining multiple datasources via rollup_join 

### ISSUE THREAD

**Issue by BjBe82** [cube-js/cube#6744]
**Describe the bug**
We are using two datasource to store data. One datasource stores initial information about a system model and the properties (mass in our testcase) and one datasource stores calculated data which was derived from the initial information. For example, sum up mass per subsystem of the engineering model. The goal is to not replicate all the initial information in the result datasource and instead join both datasources to aggregate information in the cube which can be used by a visualization frontend.

The "result" datasource only stores the configuration id(configuration_id in cube "mass_analysis_result") and this should be used to join it with the configurations (cube "elementconfiguration") in the "default" datasource to retrieve the name (and maybe more data).

I tried to setup this based on: https://cube.dev/docs/recipes/joining-multiple-data-sources, but i get the following error:
![grafik](https://github.com/cube-js/cube/assets/61700870/859e26f2-a728-4c02-8280-c5a2b55e8834)

**To Reproduce**
Perform a query like this:
```
{
  "dimensions": [
    "analysis.name",
    "analysis_run.id",
    "elementconfiguration.name"
  ],
  "measures": [
    "mass_analysis_result.mass"
  ]
}
```

**Minimally reproducible Cube Schema and .env**
```
CUBEJS_DATASOURCES=default,result
CUBEJS_DB_HOST=engineering-analysis-db
CUBEJS_DB_PORT=5432
CUBEJS_DB_NAME=engineering-analysis-db
CUBEJS_DB_USER=XXXXXXXXXXXXXXXX
CUBEJS_DB_PASS=XXXXXXXXXXXXXXXX
CUBEJS_DB_TYPE=postgres

CUBEJS_DS_RESULT_DB_HOST=analysis-result-db
CUBEJS_DS_RESULT_DB_PORT=5432
CUBEJS_DS_RESULT_DB_NAME=analysis-result-db
CUBEJS_DS_RESULT_DB_USER=XXXXXXXXXXXXXXXX
CUBEJS_DS_RESULT_DB_PASS=XXXXXXXXXXXXXXXX
CUBEJS_DS_RESULT_DB_TYPE=postgres

CUBEJS_API_SECRET=XXXXXXXXXXXXXXXX
CUBEJS_EXTERNAL_DEFAULT=true
CUBEJS_SCHEDULED_REFRESH_DEFAULT=true
CUBEJS_SCHEMA_PATH=model

# see also: https://cube.dev/docs/security
CUBEJS_JWK_URL=XXXXXXXXXXXXXXXX
```

```yaml
cubes:
  - name: elementconfiguration
    sql_table: public.elementconfiguration
    data_source: default

    pre_aggregations:
      - name: elementconfiguration_rollup
        type: rollup
        dimensions:
          - id
          - name
          - systemlevel
        indexes:
          - name: category_index
            columns:
              - id
....
 dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true
        shown: true

      - name: name
        sql: name
        type: string

      - name: systemlevel
        sql: systemlevel
        type: string

cubes:
  - name: mass_analysis_result
    sql_table: public.mass_analysis_result
    data_source: result

    pre_aggregations:
      - name: mass_analysis_result_rollup
        type: rollup
        dimensions:
          - configuration_id
          - analysis_run_id
        indexes:
          - name: category_index
            columns:
              - configuration_id

      #### NOT working https://cube.dev/docs/recipes/joining-multiple-data-sources
      - name: combined_rollup
        type: rollup_join
        dimensions:
          - elementconfiguration.name
          - elementconfiguration.systemlevel
          - analysis_run_id
        rollups:
          - elementconfiguration.elementconfiguration_rollup
          - mass_analysis_result_rollup

    joins:
....
      - name: elementconfiguration
        relationship: one_to_one
        sql: "{CUBE}.configuration_id = {elementconfiguration.id}"
....
    dimensions:
      - name: configuration_id
        sql: configuration_id
        type: number

      - name: analysis_run_id
        sql: analysis_run_id
        type: number
```

**Version:**
[0.33.25]

**Full Schema**
[cube_schema.zip](https://github.com/cube-js/cube/files/11798980/cube_schema.zip)

**Comment by BjBe82** [comment]
Thanks for the hints, this pointed me in the right direction. As it looks like the problem was 
```
    joins:
      - name: elementconfiguration
        relationship: one_to_one
        sql: "{CUBE}.configuration_id = {elementconfiguration.id}"
```
which should be 
```
    joins:
      - name: elementconfiguration
        relationship: one_to_one
        sql: "{CUBE.configuration_id} = {elementconfiguration.id}"
```
