### ISSUE TITLE
export bucket still leaves a pre-aggregation artifact in bigquery

### ISSUE THREAD

**Issue by jxperf** [cube-js/cube#6772]
Hi, the following is my understanding please let me know if I'm misunderstanding anything:
- export buckets are enabled by setting `external: true` explicitly or by setting `EXTERNAL_DEFAULT` in env vars
- when using export bucket, cube will send the pre-aggregation to say, google cloud storage instead of its default functionality of saving the pre-aggregation in the source database i.e. bigquery in my case

If my understanding on the configurations are true, then for some reason I'm still seeing the same pre-aggregation being stored on bigquery even though export buckets are enabled. Why does it do this?

**envvar config**
```
cube_api/cube-refresh-worker:
    - name: CUBEJS_DB_TYPE
      value: "bigquery"
    - name: CUBEJS_DB_BQ_PROJECT_ID
      ....
    - name: CUBEJS_DB_BQ_CREDENTIALS
      ....
    - CUBEJS_EXTERNAL_DEFAULT
      value: "true"
    - name: CUBEJS_DB_EXPORT_BUCKET
      value: {GCS bucket name}
    - name: CUBEJS_DB_EXPORT_BUCKET_TYPE
      value: "gcp"
```
