### ISSUE TITLE
ksql example simple queries fail

### ISSUE THREAD

**Issue by orgr** [cube-js/cube#6962]
**Describe the bug**
After bringing up a simple docker-compose with ksqldb, cube (and cubestore), I can't get the cube to query ksql and return results that make sense.

**To Reproduce**
1. Bringing up a docker-compose cluster with cube_api and cube_store services (api, refresh_worker, cubestore_router and 2 cubestore workers) and ksqldb-server + ksqldb-cli + redpanda (as kafka).
2. query amount of events in playground, getting 0 events
3. in ksql-cli, create streams following the  cubes from example (examples/ksql), 
```
CREATE STREAM EVENTS (TYPE VARCHAR, ANONYMOUSID VARCHAR, TIMESTAMP TIMESTAMP) with (kafka_topic='my_topic', value_format='json', partitions=1);

CREATE STREAM USERS_LAST_TIMESTAMP_NEW (ANONYMOUSID VARCHAR, MAX_TIME TIMESTAMP) with (kafka_topic='my_topic', value_format='json', partitions=1);
```
4. produce json of a new event in redpanda
```
{"TYPE": "some type", "ANONYMOUSID": "anon id", "TIMESTAMP": 1690277914000}
```
5. query `select * from events;` in ksql-cli -> getting the event above
6. query amount of events in playground, still getting 0 events

**Expected behavior**
in step 6. we'd expect to get 1 event.

**Screenshots**

**Minimally reproducible Cube Schema**
schemas are from ksql example in the examples directory in this repo, just added `data_source: "ksql",` for all schemas

.env file to add the ksql data-source:
```
CUBEJS_DS_KSQL_DB_TYPE=ksql
CUBEJS_DS_KSQL_DB_URL=http://ksqldb-server:8088
CUBEJS_DS_KSQL_DB_USER=username
CUBEJS_DS_KSQL_DB_PASS=password

CUBEJS_DATASOURCES=default,ksql
```
note - in the docker compose I built cubestore docker image locally because it crashes on my M1 Macbook
just replaced the first line in rust/cubestore/Dockerfile to
`FROM arm64v8/rust:1-bullseye as builder`

docker-compose.yml:
```
version: '3.9'

services:
  cubestore_router:
    restart: always
    image: e44a50b167a8
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_PORT=9999
      - CUBESTORE_SERVER_NAME=cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
    depends_on:
      - ksqldb-cli

  cube_api:
    restart: always
    image: cubejs/cube:latest
    ports:
      - 4000:4000
    environment:
      - CUBEJS_DB_TYPE=bigquery
      - CUBEJS_DB_BQ_PROJECT_ID=cubejs-bq-cluster
      - CUBEJS_DB_BQ_CREDENTIALS=<BQ-KEY>
      - CUBEJS_DB_EXPORT_BUCKET=cubestore
      - CUBEJS_CUBESTORE_HOST=cubestore_router
      - CUBEJS_API_SECRET=secret
      - CUBEJS_WEB_SOCKETS=true
    volumes:
      - .:/cube/conf
    depends_on:
      - cube_refresh_worker
      - cubestore_router
      - cubestore_worker_1
      - cubestore_worker_2

  cube_refresh_worker:
    restart: always
    image: cubejs/cube:latest
    environment:
      - CUBEJS_DB_TYPE=bigquery
      - CUBEJS_DB_BQ_PROJECT_ID=cubejs-bq-cluster
      - CUBEJS_DB_BQ_CREDENTIALS=<BQ-KEY>
      - CUBEJS_DB_EXPORT_BUCKET=cubestore
      - CUBEJS_CUBESTORE_HOST=cubestore_router
      - CUBEJS_API_SECRET=secret
      - CUBEJS_REFRESH_WORKER=true
    volumes:
      - .:/cube/conf

  cubestore_worker_1:
    restart: always
    image: e44a50b167a8
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_SERVER_NAME=cubestore_worker_1:10001
      - CUBESTORE_WORKER_PORT=10001
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
    depends_on:
      - cubestore_router

  cubestore_worker_2:
    restart: always
    image: e44a50b167a8
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_SERVER_NAME=cubestore_worker_2:10002
      - CUBESTORE_WORKER_PORT=10002
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
    depends_on:
      - cubestore_router

  redpanda:
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --set
    - redpanda.cluster_id=turning-red
    - --set
    - redpanda.enable_idempotence=true
    - --set
    - redpanda.enable_transactions=true
    - --set
    - redpanda.auto_create_topics_enabled=true
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    image: docker.vectorized.io/vectorized/redpanda:v21.11.11
    container_name: redpanda
    ports:
    - 9092:9092
    - 29092:29092

  ksqldb-server:
    image: confluentinc/ksqldb-server:latest
    hostname: ksqldb-server
    container_name: ksqldb-server
    depends_on:
    - redpanda
    ports:
    - "8088:8088"
    environment:
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_BOOTSTRAP_SERVERS: "redpanda:29092"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"

  ksqldb-cli:
    image: confluentinc/ksqldb-cli:latest
    container_name: ksqldb-cli
    depends_on:
    - redpanda
    - ksqldb-server
    entrypoint: /bin/sh
    tty: true
```

**Version:**
0.33.38
