### ISSUE TITLE
Unrecognized name error caused by table names not being updated in generated SQL

### ISSUE THREAD

**Issue by angenibai** [cube-js/cube#6966]
**Describe the bug**
When running a query on measures connected by join relationships in a view, the generated SQL fails to rename the cube references used in the join definitions. This causes an `Unrecognized name` error.

**To Reproduce**
I have two cubes: `example_entities` and `example_jurisdictions`. `example_jurisdictions` has a many-to-one relationship with `example_entities`, and is joined by a foreign key to the primary key in `example_entities`.

I also have a view which puts the measures and dimensions from these cubes together.

The schema is shown below:

```yaml
cubes:
  - name: example_entities
    sql: SELECT * FROM experiment.example_entities
    sqlAlias: example_entities
    measures:
      - name: income
        sql: income
        type: sum
    dimensions:
      - name: pk_example_entities
        sql: pk_example_entities
        type: string
        primary_key: true
        public: true
      - name: name
        sql: name
        type: string

  - name: example_jurisdictions
    sql: SELECT * FROM experiment.example_jurisdictions
    sqlAlias: example_jurisdictions
    measures:
      - name: roads
        sql: roads
        type: sum
    dimensions:
      - name: pk_example_jurisdictions
        sql: pk_example_jurisdictions
        type: string
        primary_key: true
        public: true
      - name: fk_example_entities
        sql: fk_example_entities
        type: string
      - name: jurisdiction
        sql: jurisdiction
        type: string
    joins:
      - name: example_entities
        relationship: many_to_one
        sql: example_jurisdictions.fk_example_entities = example_entities.pk_example_entities

views:
  - name: example_view
    description: all data from example
    cubes:
      - join_path: example_entities
        includes:
          - name
          - income
      - join_path: example_jurisdictions
        includes:
          - jurisdiction
          - roads
```

When I use Cube Playground, querying the `name` and `jurisdiction` dimensions together works fine, but attempting to query all dimensions and measures together (`name`, `jurisdiction`, `income`, `roads`) causes this error:

```
Unrecognized name: example_jurisdictions; Did you mean pk_example_jurisdictions? at [2:70]
```

Looking at the generated SQL, you can see that the error is because the table for `example_jurisdictions` is renamed to `main__example_jurisdictions`. However, the reference to `example_jurisdictions` in the SQL for the join definition is not updated to reflect this renaming.

```sql
SELECT
  q_0.`example_view__name`,
  q_0.`example_view__jurisdiction`,
  `example_entities__income` `example_view__income`,
  `example_jurisdictions__roads` `example_view__roads`
FROM
  (
    SELECT
      `main__example_entities`.name `example_view__name`,
      `main__example_jurisdictions`.jurisdiction `example_view__jurisdiction`,
      sum(`main__example_jurisdictions`.roads) `example_jurisdictions__roads`
    FROM
      experiment.example_jurisdictions AS `main__example_jurisdictions`
      LEFT JOIN experiment.example_entities AS `main__example_entities` ON example_jurisdictions.fk_example_entities = example_entities.pk_example_entities
    GROUP BY
      1,
      2
  ) as q_0
  INNER JOIN (
    SELECT
      `keys`.`example_view__name`,
      `keys`.`example_view__jurisdiction`,
      sum(`example_entities_key__example_entities`.income) `example_entities__income`
    FROM
      (
        SELECT
          DISTINCT `example_entities_key__example_entities`.name `example_view__name`,
          `example_entities_key__example_jurisdictions`.jurisdiction `example_view__jurisdiction`,
          `example_entities_key__example_entities`.pk_example_entities `example_entities__pk_example_entities`
        FROM
          experiment.example_jurisdictions AS `example_entities_key__example_jurisdictions`
          LEFT JOIN experiment.example_entities AS `example_entities_key__example_entities` ON example_jurisdictions.fk_example_entities = example_entities.pk_example_entities
      ) AS `keys`
      LEFT JOIN experiment.example_entities AS `example_entities_key__example_entities` ON `keys`.`example_entities__pk_example_entities` = `example_entities_key__example_entities`.pk_example_entities
    GROUP BY
      1,
      2
  ) as q_1 ON (
    q_0.`example_view__name` = q_1.`example_view__name`
    OR (
      q_0.`example_view__name` IS NULL
      AND q_1.`example_view__name` IS NULL
    )
  )
  AND (
    q_0.`example_view__jurisdiction` = q_1.`example_view__jurisdiction`
    OR (
      q_0.`example_view__jurisdiction` IS NULL
      AND q_1.`example_view__jurisdiction` IS NULL
    )
  )
ORDER BY
  4 DESC
LIMIT
  5000
```

**Expected behavior**
Cube being able to update all references when a table is renamed, so that joined cubes can be presented through views.

If this is not able to fixed, is there some other way that I can model the data so that I am able to join the cubes without running into errors?

**Version:**
0.33.31
