### ISSUE TITLE
Refresh worker got error of AWS S3 error: custom: missing field `Bucket`

### ISSUE THREAD

**Issue by tinolyu** [cube-js/cube#6997]
**Problem**

I'm running cube in k8s. The api instance and cube store instance are running without errors, the cache could be uploaded to s3. But I got this error in refresh worker after several hours:
```
{"message":"Refresh Scheduler Error","error":"Error: Error during upload of prod_pre_aggregations.<table>_count_by_os_cczniyb3_xfs1bj4c_1icqlhs-0.csv.gz create table: CREATE TABLE prod_pre_aggregations.dim_device_count_by_os_cczniyb3_xfs1bj4c_1icqlhs (`<table>__os` varchar(255), `<table>__count` bigint): Internal: AWS S3 error: custom: missing field `Bucket`","securityContext":{},"requestId":"scheduler-e4ea819c-304a-403a-af01-8fbc2ff4313e"}
```

**Refresh worker config**
```yaml
- name: CUBEJS_DB_TYPE
  value: "athena"
- name: CUBEJS_AWS_REGION
  value: "us-west-2"
- name: CUBEJS_AWS_ATHENA_CATALOG
  value: "AwsDataCatalog"
- name: CUBEJS_AWS_S3_OUTPUT_LOCATION
  value: "s3://<bucket>"
- name: CUBEJS_PG_SQL_PORT
  value: "15432"
- name: CUBEJS_SQL_USER
  value: "<user>"
- name: CUBEJS_SQL_PASSWORD
  value: "<password>"
- name: CUBEJS_REFRESH_WORKER
  value: "true"
- name: CUBEJS_CUBESTORE_HOST
  value: "router"
```
I've tried adding CUBESTORE_S3_BUCKET env var but it shows the same error. Is there any solution to fix this error?
