### ISSUE TITLE
external  pre_aggregations with cubestore ER_INTERNAL_ERROR: Custom type 'timestamptz' is not supported

### ISSUE THREAD

**Issue by iiq374** [cube-js/cube#7017]
**Describe the bug**
I'm using CubeJS connecting Postgres. When integrating Cube Store I got the error with timestamptz type of Postgres

```
ERROR [cubestore::http] <pid:1> Error processing HTTP command: Custom type 'timestamptz' is not supported
```

**To Reproduce**
1. Create a Pre-Aggregation with a TimestampTZ datatype as a dimension
2. Wait for Pre-Aggregation to build
3. Observe error in logs

**Expected behavior**
Postgres Timestamptz should not cause CubeStore to be unusable

**Screenshots**

**Version:**
0.33.43

**Additional context**
Seems related to this earlier issue / related fix:  https://github.com/cube-js/cube/issues/1796

**Comment by paveltiunov** [comment]
@iiq374 There's no timestamptz type in Cube Store, so you should cast it to timestamp first if you're using it as the raw value of a dimension. If you put in a time dimension, it should work just fine.

**Comment by nurulhudaapon** [comment]
@paveltiunov Where should I cast the value? Should I create a new dimension with a value casted to `timestamp` or just casting the existing time dimension will be fine (assuming it wont' affect timezone)?

**Comment by igorlukanin** [comment]
@nurulhudaapon Here's what I believe Pavel meant.

```yaml
    dimensions:
        # It's OK to have a TIMESTAMPZ value as a time dimension, it will work just fine
      - name: created_at
        sql: created_at
        type: time

        # You have to cast it to `TIMESTAMP` if you'd like to use it in a non-`time` dimension
      - name: created_at_raw
        sql: "created_at::TIMESTAMP"
        type: string
```
