### ISSUE TITLE
Cube Trino Run Slow

### ISSUE THREAD

**Issue by zongkx** [cube-js/cube#7049]
**Problem**

docker logs:
2023-08-19 17:19:37 Performing query completed: ce333754-7ab0-4719-932d-3a161b1dab1d-span-1 (3419ms)
2023-08-19 17:19:37 Load Request Success: ce333754-7ab0-4719-932d-3a161b1dab1d-span-1 (3459ms)

This simple sql  executes very fast in the database client. 
my cubejs docker env is
```
CUBEJS_DATASOURCES=default
CUBEJS_DEV_MODE=true
CUBEJS_WEB_SOCKETS=false
CUBEJS_DB_TYPE=trino
CUBEJS_DB_HOST=****
CUBEJS_DB_PORT=28443
CUBEJS_DB_USER=test
CUBEJS_DB_CATALOG=memory
CUBEJS_DEV_MODE=true
CUBEJS_DB_SSL=true
CUBEJS_DB_PASS=****
```

**Related Cube.js schema**
```yml
cubes:
  - name: memory_default_mysql_vte_deals
    sql_table: memory.default.mysql_vte_deals
    data_source: default
    joins: []
    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true
      - name: type
        sql: type
        type: string
```

**Related Cube.js generated SQL**

```sql
SELECT
  "memory_default_mysql_vte_deals".id "memory_default_mysql_vte_deals__id"
FROM
  memory.default.mysql_vte_deals AS "memory_default_mysql_vte_deals"
GROUP BY
  1
ORDER BY
  1 ASC
LIMIT
  10000
```
