### ISSUE TITLE
Conditionally filter a measure, according to how the cubes were joined

### ISSUE THREAD

**Issue by NicoRyberg** [cube-js/cube#7090]
**Problem**

I have a "score_option"  dimension cube with two possible ways to join with my fact table: either by the "score_option_id" column or by the "score_option_group_id" column. If I join by "group_id" it is a many to many relationship and is relevant to know which scores have a 0 count.
The issue I have is that when I join by group_id, it causes duplication of fact records due to a many-to-many relation. In that case, I must apply a filter to the measures: {CUBE}.score_option_id = {dim_score_option__join_on_score_group_id}.id.

Currently, I have 2 duplicated cube definitions for my dim score_option table, and two join definitions on my fact table. One by "id" and one by "group_id". Then, I have all my measures duplicated to add the filter, and the development team knows it should use the measures with the filter if they use any dimension on the cube joined by group_id.

**What I want to know:** Am I on the wrong path to solve this problem? Is there any less hacky way to do this? If there isn't, can I add the filters to the measures conditionally, if the join was made by group_id?

**Related Cube.js schema**
```yaml
cubes:
  - name: fact_observation_results
    sql_table: dw.fact_observation_results
    data_source: default

    joins:
      - name: dim_score_option__join_on_score_group_id
        sql: "split_part({dim_score_option__join_on_score_group_id}.id, '.', 1) = {CUBE}.lookfor_id"
        relationship: many_to_one

      - name: dim_score_option
        sql: "{CUBE}.score_option_id = {dim_score_option}.id"
        relationship: many_to_one

    dimensions:
      - name: lookfor_result_id
        sql: lookfor_result_id
        type: string
        primary_key: true
        public: true

      - name: score_option_id
        sql: score_option_id
        type: string
     # ...

    measures:
      - name: count
        type: count 

      - name: count__dim_score_option__join_on_score_group_id
        type: count
        filters:
          - sql: "{CUBE}.score_option_id = {dim_score_option__join_on_score_group_id}.id"

      # ... all my other measures
      
  - name: dim_score_option__join_on_score_group_id
    sql_table: dw.dim_score_option
    data_source: default

    dimensions:
      - name: id
        sql: id
        type: string
        primary_key: true
     # ...

  - name: dim_score_option
    sql_table: dw.dim_score_option
    data_source: default

    dimensions:
      - name: id
        sql: id
        type: string
        primary_key: true
     # ...
```
