### ISSUE TITLE
Views with proxy dimensions don't not match pre-aggregations

### ISSUE THREAD

**Issue by igorlukanin** [cube-js/cube#7099]
**Describe the bug**
When a view references a *proxy dimension*, a query that includes that dimension would not match pre-aggregations; however, the same query against respective cube members would match the pre-aggregation.

**To Reproduce**
1. Use the following data model
```yml
cubes:
  - name: other_cube
    sql: SELECT 123 AS id, 456 AS value

    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true

      - name: value
        sql: value
        type: number

  - name: cube
    sql: SELECT 123 AS id, 123 AS other_id, 789 AS value

    joins:
      - name: other_cube
        relationship: one_to_one
        sql: "{CUBE.other_id} = {other_cube.id}"

    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true

      - name: other_id
        sql: other_id
        type: number

      - name: other_value
        sql: "{other_cube.value}"
        type: number

    pre_aggregations:
      - name: main

        dimensions:
          - id
          - other_value

views:
  - name: view
    
    cubes:
      - join_path: cube
        
        includes:
          - id
          - other_value
```
2. Run the following query—it would match the pre-aggregation
```json
{
  "dimensions": [
    "cube.id",
    "cube.other_value"
  ]
}
```
3. Run another query—it **would not** match the pre-aggregation
```yml
{
  "dimensions": [
    "view.id",
    "view.other_value"
  ]
}
```

**Expected behavior**
According to [pre-aggregation selection rules](https://cube.dev/docs/product/caching/getting-started-pre-aggregations#selecting-the-pre-aggregation), both queries should match the pre-aggregation.

**Screenshots**
<img width="926" alt="Screenshot 2023-09-04 at 22 47 59" src="https://github.com/cube-js/cube/assets/3852894/3374525d-9282-4bef-b324-ce78d5dfba25">
<img width="927" alt="Screenshot 2023-09-04 at 22 48 14" src="https://github.com/cube-js/cube/assets/3852894/b2fc32cc-b709-47f0-b9a4-477428e13105">

**Version:**
0.33.41
