### ISSUE TITLE
"excludes" doesn't work in views when references cube has a prefix or an alias  

### ISSUE THREAD

**Issue by igorlukanin** [cube-js/cube#7100]
**Describe the bug**
In a view, `excludes` would not actually exclude members of a referenced cube if that cube is defined with `prefix: true` or some `alias`.

**To Reproduce**
1. Use the following data model
```yml
cubes:
  - name: other_cube
    sql: SELECT 123 AS id

    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true

  - name: cube
    sql: >
      SELECT 1 AS id, 123 AS other_id UNION
      SELECT 2 AS id, 123 AS other_id

    joins:
      - name: other_cube
        relationship: one_to_one
        sql: "{CUBE.other_id} = {other_cube.id}"

    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true

      - name: other_id
        sql: other_id
        type: number

views:
  - name: view

    cubes:
      - join_path: cube
        includes: "*"

        excludes:
          - id

      - join_path: cube.other_cube
        prefix: true
        # alias: another
        includes: "*"

        excludes:
          - id
```
2. Check the members of the view in Playground—there will be two of them.

**Expected behavior**
Out of 3 dimensions, only `other_id` should be included in the view.

**Screenshots**
<img width="712" alt="Screenshot 2023-09-04 at 23 09 02" src="https://github.com/cube-js/cube/assets/3852894/8371b5b2-b1bc-434d-8fd4-0a6d6c2aa6bc">

**Version:**
0.33.41
