### ISSUE TITLE
PG_SQL - ERROR: Internal: Unexpected panic. Reason: failed printing to stdout: Resource temporarily unavailable (os error 11)

### ISSUE THREAD

**Issue by gojumprope** [cube-js/cube#7104]
**Describe the bug**
SQL Error [XX000]: ERROR: Internal: Unexpected panic. Reason: failed printing to stdout: Resource temporarily unavailable (os error 11)
thread 'tokio-runtime-worker' panicked at 'failed printing to stdout: Resource temporarily unavailable (os error 11)', library/std/src/io/stdio.rs:956:9
{"message":"Cube SQL Error","error":"Error during processing PostgreSQL message: Internal: Unexpected panic. Reason: failed printing to stdout: Resource temporarily unavailable (os error 11)","appName":"DBeaver 23.1.4 - SQLEditor <Script-19.sql>","apiType":"sql","protocol":"postgres"}

**To Reproduce**
1. DBeaver connect Cube postgres SQL
2. Run query  
3. See error

**Expected behavior**
Sometime able to get the data but sometime throw this error

**Screenshots**
![image](https://github.com/cube-js/cube/assets/38604290/616c2149-8778-44ab-9242-3c55d69d34b2)

**Version:**
0.32.25

**Comment by igorlukanin** [comment]
@gojumprope Thanks for reporting!

> Sometime able to get the data but sometime throw this error

Were you able to identify features of queries that are more likely to result in such an error? Any additional information that you might have would be helpful to track this down.

**Comment by ovr** [comment]
Did you configure `CUBEJS_LOG_LEVEL`? If yes, what value did you specify? `TRACE`?

refs https://github.com/cube-js/cube/pull/6272

**Comment by gojumprope** [comment]
> Did you configure `CUBEJS_LOG_LEVEL`? If yes, what value did you specify? `TRACE`?
> 
> refs #6272

no, we didn't configure CUBEJS_LOG_LEVEL.

I have found this issue was due to we want to get minimum time in the cube measure, when we set min for the time column, it returns number in Posgres SQL, and every rows return null, so we change the data type into time in cube measures and it able to returns string in Posgres SQL without the error again. However, it should return time datatype instead of string

Before:
measures:
MinTime: {
            sql: `__time`,
            type: `min`,
 }, 

After:
measures:
MinTime: {
            sql: `Min(__time)`,
            type: `time`,
 },

**Comment by igorlukanin** [comment]
Indeed, with the following data mode...

```yaml
cubes:
  - name: test
    sql: > 
      SELECT '2024-01-15T00:00:00.000Z'::TIMESTAMP AS timestamp UNION ALL
      SELECT '2024-02-15T00:00:00.000Z'::TIMESTAMP AS timestamp UNION ALL
      SELECT '2024-03-15T00:00:00.000Z'::TIMESTAMP AS timestamp
 
    measures:
      - name: min_time
        sql: timestamp
        type: min

      - name: min_time_2
        sql: MIN(timestamp)
        type: time
```

...running the following query against the SQL API...

```sql
SELECT MEASURE(min_time), MEASURE(min_time_2) FROM test;
```

...will yield the following result:

<img width="857" alt="Screenshot 2024-10-09 at 00 24 43" src="https://github.com/user-attachments/assets/6665cccb-dca7-43db-a417-952e5af8e525">

While one might expect `MEASURE(min_time)` to return the same value as `MEASURE(min_time_2)`, this is actually the intended behavior. At least, this is how it's currently implemented: according to [docs](https://cube.dev/docs/reference/data-model/types-and-formats#min), `min` and similar functions are only intended to work with numeric values as of now.

Since this seems to be a duplicate of https://github.com/cube-js/cube/issues/8153, let me close this one in favor of that one. I believe supporting time values for `min`/`max` measures makes for a nice feature request.
