### ISSUE TITLE
Empty quoted strings lead to an error in YAML data models

### ISSUE THREAD

**Issue by igorlukanin** [cube-js/cube#7126]
**Describe the bug**
Consider the following data model:
```yml
  - name: test
    sql: SELECT 123
    description: ''
    title: ""

    measures:
      - name: count
        type: count
```

It will fail to compile with the following error:
```
TypeError: Cannot read properties of undefined (reading '0')
at YamlCompiler.transpileYaml (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/YamlCompiler.ts:160:23)
at YamlCompiler.transpileYaml (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/YamlCompiler.ts:171:28)
...
```

Most probably, this is because an empty string in `description` or `title` will be parsed as `null`.

When generating YAML dynamically with Jinja, it's quite possible that an empty string will be generated:
```yml
  - name: "{{ cube.name }}"
    sql: "{{ cube.sql }}"
    description: "{{ cube.description }}"
    title: "{{ cube.title }}"

    measures:
      - name: count
        type: count
```

YAML specification provides a workaround, however, it doesn't work with Cube as well—same error happens:
```yml
  - name: !!str "{{ cube.name }}"
    sql: !!str "{{ cube.sql }}"
    description: !!str "{{ cube.description }}"
    title: !!str "{{ cube.title }}"

    measures:
      - name: count
        type: count
```

**To Reproduce**
See above.

**Expected behavior**
Empty quoted strings should just work in YAML data models.

**Version:**
0.33.53
