### ISSUE TITLE
Joins are not inherited (when `extends` is used)

### ISSUE THREAD

**Issue by igorlukanin** [cube-js/cube#7137]
**Describe the bug**
From the docs:
> The usual pattern is to extract common measures, dimensions, and **joins** into the base cube and then extend from the base cube

However, joins are not indeed inherited.

**To Reproduce**
1. Use this data model:
```yaml
cubes:
  - name: cube_joined
    sql: SELECT 123 AS id, 456 AS value

    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true

      - name: value
        sql: value
        type: number

  - name: cube_parent
    sql: SELECT 1 AS id, 123 AS joined_id, 789 AS value

    joins:
      - name: cube_joined
        relationship: one_to_one
        sql: "{CUBE.joined_id} = {cube_joined.id}"

    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true

      - name: joined_id
        sql: joined_id
        type: number

      - name: value
        sql: value
        type: number

  - name: cube_child
    extends: cube_parent
```
2. Run the following query—it will work:
```json
{
  "dimensions": [
    "cube_parent.value",
    "cube_joined.value"
  ]
}
```
3. Then, run the following query—it will fail:
```json
{
  "dimensions": [
    "cube_child.value",
    "cube_joined.value"
  ]
}
```
Error:
<img width="564" alt="Screenshot 2023-09-15 at 14 33 44" src="https://github.com/cube-js/cube/assets/3852894/c2b459d8-3655-4cf2-b3f2-295b90a61e1e">

**Expected behavior**
Last query should succeed since `cube_child` should inherit everything from `cube_parent`. 

**Version:**
0.33.52
