### ISSUE TITLE
Number fields do not work in YAML data models meta

### ISSUE THREAD

**Issue by jonaslimads** [cube-js/cube#7150]
**Describe the bug**
Consider the following YAML cube:

```yaml
cubes:
  - name: my_cube
    sql_table: my_table

    dimensions:
      - name: agent_name
        title: Agent Name
        sql: agent_name
        type: string
        meta:
          works: "123"
          does_not_work: 456
          does_not_work_either: !!int 789
```

It fails to compile with the error:

```
Unexpected input during yaml transpiling: 456
```

If I remove the line `does_not_work: 456`, it fails with

```
Unexpected input during yaml transpiling: 789
```

So neither `456` or `!!int 789` works.

Thank you!

**To Reproduce**
See above

**Expected behavior**
Number fields should just work in YAML data models

**Minimally reproducible Cube Schema**
See above

**Version:**
0.33.25
