### ISSUE TITLE
Support GRANULARITY in FILTER_PARAMS?

### ISSUE THREAD

**Issue by maiqingqiang** [cube-js/cube#7163]
Support GRANULARITY in FILTER_PARAMS?

maybe more simple:

| id | status | created_at              | updated_at                |
|----|--------|-------------------------|---------------------------|
| 1  | 200    | 2021-01-01 14:44:36.425 | 2021-01-01 14:44:36.425   |
| 2  | 404    | 2021-01-01 09:30:10.000 | 2021-01-01 09:30:10.000   |
| 3  | 200    | 2021-01-02 12:44:36.211 | 2021-01-02 12:44:36.211   |
| 4  | 200    | 2021-01-02 14:34:21.234 | `2021-06-02 14:34:21.234` |
| 5  | 500    | 2021-01-02 15:46:43.123 | 2021-01-02 15:46:43.123   |
| 6  | 200    | 2021-01-02 15:46:43.025 | 2021-01-02 15:46:43.025   |
| 7  | 200    | 2021-01-02 16:44:36.135 | 2021-01-02 16:44:36.135   |
| 8  | 404    | 2021-01-02 16:59:01.415 | 2021-01-02 16:59:01.415   |
| 9  | 200    | 2021-01-02 17:32:16.398 | `2021-07-02 17:32:16.398` |
| 10 | 200    | 2021-01-03 18:29:27.395 | 2021-01-03 18:29:27.395   |

I'd like to use "created_at" as the primary time dimension, "updated_at" as the sub-time dimension,
and align the time granularity of "created_at" with the time range of "updated_at".

For status code = 200, it should be:

created_at:[2021-01-01,2021-01-31]
granularity = day

Jan 01: 1  updated_at:[2021-01-01,2021-01-01]
Jan 02: 3  updated_at:[2021-01-02,2021-01-02]
Jan 03: 1  updated_at:[2021-01-03,2021-01-03]

created_at:[2021-01-01,2021-12-31]
granularity = month
Jan: 5  updated_at:[2021-01-01,2021-01-31]
Feb: ...  updated_at:[2021-02-01,2021-02-28]
...

How to achieve this? 

Thanks

Below is my approach, but it requires defining numerous measures.
```yaml
cubes:
  - name: status_talbe
    title: Status Talbe
    ...
    measures:
      - name: status_200_cnt_daily
        ...
        filters:
          - sql: "status = 200"
          - sql: "({CUBE.updated_at} >= DATE_FORMAT(CONVERT_TZ({CUBE.created_at}, @@session.time_zone, '+00:00'),'%Y-%m-%dT00:00:00.000') AND {CUBE.updated_at} < DATE_FORMAT(DATE_ADD(CONVERT_TZ({CUBE.created_at}, @@session.time_zone, '+00:00'),INTERVAL 1 DAY),'%Y-%m-%dT00:00:00.000'))"
        type: countDistinct

      - name: status_200_cnt_monthly
        ...
        filters:
          - sql: "status = 200"
          - sql: "({CUBE.updated_at} >= DATE_FORMAT(CONVERT_TZ({CUBE.created_at}, @@session.time_zone, '+00:00'),'%Y-%m-01T00:00:00.000') AND {CUBE.updated_at} < DATE_FORMAT(DATE_ADD(CONVERT_TZ({CUBE.created_at}, @@session.time_zone, '+00:00'),INTERVAL 1 MONTH),'%Y-%m-01T00:00:00.000'))"
        type: countDistinct
        public: false
```

My expectations:

```yaml
cubes:
  - name: status_talbe
    title: Status Talbe
    ...
    measures:
      - name: status_200_cnt
        ...
        filters:
          - sql: "status = 200"
          - sql: "
          CASE 
	WHEN {FILTER_PARAMS.created_at.time_dimensions.granularity}== 'day' THEN ({CUBE.updated_at} >= DATE_FORMAT(CONVERT_TZ({CUBE.created_at}, @@session.time_zone, '+00:00'),'%Y-%m-%dT00:00:00.000') AND {CUBE.updated_at} < DATE_FORMAT(DATE_ADD(CONVERT_TZ({CUBE.created_at}, @@session.time_zone, '+00:00'),INTERVAL 1 DAY),'%Y-%m-%dT00:00:00.000'))
	WHEN {FILTER_PARAMS.created_at.time_dimensions.granularity}== 'month' THEN ({CUBE.updated_at} >= DATE_FORMAT(CONVERT_TZ({CUBE.created_at}, @@session.time_zone, '+00:00'),'%Y-%m-01T00:00:00.000') AND {CUBE.updated_at} < DATE_FORMAT(DATE_ADD(CONVERT_TZ({CUBE.created_at}, @@session.time_zone, '+00:00'),INTERVAL 1 MONTH),'%Y-%m-01T00:00:00.000'))
	ELSE  END
          "
        type: countDistinct
```
