### ISSUE TITLE
Is Pre-Aggregation datetime columns meant to be of data_type text in cubestore?

### ISSUE THREAD

**Issue by chull434** [cube-js/cube#7278]
**Problem**

Queries with Pre-Aggregations return no data
I have checked cubestore with mysql and there is the correct data in the pre-aggregations table 
However the query below returns no results, I believe due to the where clause date range
Is the datetime column meant to be a data_type of text??

or am I doing something wrong setting up my pre-aggregations cause this isn't working for me

**Related Cube.js schema**
```yaml
pre_aggregations:
  - name: data_rollup
    measures:
      - CUBE.seats
    timeDimension: CUBE.timeSeries
    granularity: month
```

**Related Cube.js generated SQL**

```mysql
SELECT `data__timeseries_month` `data__timeseries_month`, sum(`data__seats`) `data__seats` 
FROM dev_pre_aggregations.data_data_rollup_4qr3o3ed_ug1l0u2v_1ij0scj AS `data__data_rollup`  
WHERE (`data__timeseries_month` >= to_timestamp('2022-01-01T00:00:00.000') AND `data__timeseries_month` <= to_timestamp('2022-12-31T23:59:59.999')) 
GROUP BY 1
ORDER BY 1 ASC 
LIMIT 5000
```

Latest version - Cube Store (0.33.10)
