### ISSUE TITLE
Cannot use use_original_sql_pre_aggregations on Postgres

### ISSUE THREAD

**Issue by TobiasMaehl-pIX** [cube-js/cube#7421]
**Describe the bug**
We would like to reuse an original_sql pre-aggregation stored in Postgres in a rollup pre-aggregation. Setting `use_original_sql_pre_aggregations: true` fails with the following error message during scheduled refresh:
> {"message":"Refresh Scheduler Error","error":"Error: relation \"pre_agg_tenant_123.base_positions_main\" does not exist",

**Expected behavior**
It should be possible to reuse the original_sql pre-aggregation stored in Postgres, as stated in the docs. We have a heavy sql query in the original data model.

**Minimally reproducible Cube Schema**
```yaml
cubes:
  - name: base_positions
    public: false
    sql: SELECT "id_1" AS position_id, "test" AS position_name
measures:
  - name: position_count
    type: count
dimensions:
  - name: position_id
    sql: position_id
    type: string
    primary_key: true
  - name: position_name
    sql: position_name
    type: string
  - name: position_date
    sql: "date"
    type: time

pre_aggregations:
  - name: main
    type: original_sql
    external: false
  - name: positions_per_month
    measures:
      - CUBE.position_count
    time_dimension: CUBE. position_date
    granularity: month
    use_original_sql_pre_aggregations: true
```

**Version:**
0.34.19
