### ISSUE TITLE
missing semicolon on cubes/orders.yml - when adding a pre-aggregation

### ISSUE THREAD

**Issue by pinale** [cube-js/cube#7473]
following the getting started tutorial https://cube.dev/docs/product/getting-started/core/create-a-project with the built-in database 
when i add a pre-aggregation i get this error
![error](https://github.com/cube-js/cube/assets/11770155/5ee5efe1-25c4-4cac-acd7-c8801ac6bc5a)

i've tried to add the pre-aggregation code snippet to the `cubes/orders.yml` (manually) as well but in this case the error is:
Error during upload of dev_pre_aggregations.orders_main_11f2gsdh_2ee4v4df_1ime8pq-0.csv.gz create table: CREATE TABLE dev_pre_aggregations.orders_main_11f2gsdh_2ee4v4df_1ime8pq (`orders__status` varchar(255), `orders__created_at_day` timestamp, `orders__count` bigint): Internal: No such file or directory (os error 2)

cubes/orders.yml
```
cubes:
  - name: orders
    sql_table: public.orders
    data_source: default

    joins: []

    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true

      - name: status
        sql: status
        type: string

      - name: created_at
        sql: created_at
        type: time

      - name: completed_at
        sql: completed_at
        type: time

    measures:
      - name: count
        type: count

      - name: number
        sql: number
        type: sum

    pre_aggregations:
      - name: main
        measures:
          - orders.count
        dimensions:
          - orders.status
        timeDimension: orders.created_at
        granularity: day
```
