### ISSUE TITLE
Model JSON datatype dimension column in Cube  

### ISSUE THREAD

**Issue by MadhusudanN** [cube-js/cube#7514]
I could see that the below data types are supported for dimension type in the Cube docs.(https://cube.dev/docs/reference/data-model/types-and-formats#dimension-types)

- time
- string
- number
- boolean
- geo

Can someone please let me know is there a support for dimension columns of "JSON" datatype.

**Comment by MadhusudanN** [comment]
Hi, Can you share any document link which mentions about this. Sorry I did not find the doc in Cube documentation.
The usecase here is I need to perform search/sort/aggregate operations on nested fields of JSON string stored in a dimension column which is of 'JSON'  type. 
Please share any relevant document which explains the same.

**Comment by mharrisb1** [comment]
Afaik, your best option would be use the [`sql` parameter](https://cube.dev/docs/reference/data-model/cube#sql) in your  cube definition file(s) and extract the fields you care about in a select statement. Then you can reference those columns for the cube dimensions and measures.

## Example

If we had a table called `my_table` that has a column in it called `json_obj` that contains JSON objects and each JSON object looks like this:

```json
{
  "foo": 1,
  "bar": true,
  "fizz": "buzz"
}
```

You could do something like this (assumes Snowflake dialect, but most DBs will have the ability to parse JSON):

```yml
cubes:
  - name: my_table
    sql: >
      select
        cast(json_obj:foo as integer) as foo,
        cast(json_obj:bar as boolean) as bar,
        cast(json_obj:fizz as varchar) as fizz
      from my_table
    dimensions:
      - name: foo
        sql: foo
        type: number
      - name: bar
        sql: bar
        type: boolean
      - name: fizz
        sql: fizz
        type: string
```

## Simpler Alternative

If the data is just going to be consumed by some other downstream service and that service, then you can just mark the field as type `string` and the value should just be returned as a JSON string.
