### ISSUE TITLE
Getting Unsupported filter scalar: int32(3) while executing query which filters dayofweek

### ISSUE THREAD

**Issue by anshjain18** [cube-js/cube#7598]
**Failed SQL**
```sql
select
  'b2c_orders' as metric_name,
  measure(b2c_orders) as metric_value,
  date_trunc('week', time) as time
from product_revenue 
where dayofweek <= EXTRACT(DOW from current_date)
GROUP by 1,3
```

**Logical Plan**
Not able to get the logical plan, getting the same error while appending "explain" keyword to the query.

**Error**
postgresql error: Error during rewrite: Unexpected panic. Reason: Unsupported filter scalar: Int32(4). Please check logs for additional information.

**Version:**
0.34.36

**Additional context**

1. dayofweek is a simple dimension of type number in the cube 'product_revenue'
2. If I use a constant value on the either side of the filter, for eg: '2 <=  EXTRACT(DOW from current_date)',  or 'dayofweek <= 2', it works just fine.

**Comment by igorlukanin** [comment]
Hi @anshjain18 👋 Thanks for reporting this! I haven't been able to find a workaround yet. Cc'ing @ovr and @paveltiunov so they might take a look.

**Comment by anshjain18** [comment]
Hey @igorlukanin @paveltiunov , can u please confirm if there is any update on this..

**Comment by igorlukanin** [comment]
I was able to reproduce this in Cube Cloud on v0.36.7 (latest) with the query pushdown on, same behavior as reported:

<img width="1278" alt="Screenshot 2024-10-08 at 23 42 21" src="https://github.com/user-attachments/assets/4a822c84-fca8-476b-8130-452b59b1fc6b">

Data model that I used:

```yaml
cubes:
  - name: product_revenue
    sql: SELECT '2025-01-15Z'::TIMESTAMPZ AS time, 1 AS dayofweek

    dimensions:
      - name: time
        sql: time
        type: time

      - name: dayofweek
        sql: dayofweek
        type: number

    measures:
      - name: b2c_orders
        type: count
```
