### ISSUE TITLE
Duplicate queries running on Underlying database(Snowflake) for pre-aggregations

### ISSUE THREAD

**Issue by anshjain18** [cube-js/cube#7641]
**Describe the bug**
I have defined the following simple pre-aggregation for my cube
```
  measures: 
    - CUBE.measure_1
  dimensions:
    - CUBE.dimension_1
    - CUBE.dimension_2
  time_dimension: time
  granularity: day 
  partition_granularity: month
  build_range_start:
    sql: SELECT CURRENT_DATE - INTERVAL '200 day'
  build_range_end:
    sql: SELECT CURRENT_DATE
  refresh_key:
    every: 1 day
    incremental: true
    update_window: 40 day
  allow_non_strict_date_range_match: true
```

1. Now, when this definition was first added, I expected that Cube will run 8 queries on Snowflake (1 for each month) to cover 200 days.
2. But instead it runs 16 queries, and what confuses me more is that out of those 16 queries 8 are exactly similar to the other 8 and produce the exact same results.
3. This pattern is also followed whenever I make a small change in the pre-agg definition like adding or removing a segment. It will run 16 queries instead of expected 8.

**Expected behavior**
1. Only the required number of queries should run on Cube

**Version:**
0.34.40

**Additional context**
1. Running Cube in **development** environment using the Kubernetes chart given by: https://artifacthub.io/packages/helm/gadsme/cube
2. Underlying database = Snowflake
3. Also using cubestore k8 chart https://artifacthub.io/packages/helm/gadsme/cubestore
