### ISSUE TITLE
Submeasures of calculated measures not wrapped in brackets

### ISSUE THREAD

**Issue by tehunter** [cube-js/cube#7667]
**Describe the bug**
When generating SQL for a calculated measure, cube does not currently wrap the submeasure SQL leading to unexpected results due to order of operations precedence.

**To Reproduce**
See reproducible schema below

**Expected behavior**
Submeasures are wrapped in parentheses/brackets to ensure correct order of operations. In the example below, the expected value is `(1 + 2) / ((0.5 + 1.0) + (2.0 + 2.5)) = (3 / 6) = 0.5` rather than `((1 + 2) / (0.5 + 1.0)) + (2.0 + 2.5) = (3 / 1.5) + 4.5) = 6.5`

**Screenshots**
![image](https://github.com/cube-js/cube/assets/7980666/be78ca3e-caee-403f-95eb-83cb9c3c6311)

**Minimally reproducible Cube Schema**
```yaml
cubes:
  - name: test_calculated
    sql: |
     SELECT * FROM VALUES
      (1.0, 0.5, 2.0, 'A'),
      (2.0, 1.0, 2.5, 'B')
     my_values(value, weight, weight_2, value_group)
    measures:
      - name: value
        type: number
        sql: SUM(value)
      - name: composite_weight
        type: number
        sql: >
          SUM(weight)
          + SUM(weight_2)
      - name: weighted_value
        type: number
        sql: "{value} / {composite_weight}"
```

**Version:**
0.34.43

**Additional context**
Here is the generated code per the Cube Playground:
```sql
SELECT
  SUM(value) "test_calculated__value",
  SUM(weight) + SUM(weight_2) "test_calculated__composite_weight",
  SUM(value) / SUM(weight) + SUM(weight_2) "test_calculated__weighted_value"
FROM
  (
    SELECT
      *
    FROM
    VALUES
      (1.0, 0.5, 2.0, 'A'),
      (2.0, 1.0, 2.5, 'B') my_values(value, weight, weight_2, value_group)
  ) AS "test_calculated"
LIMIT
  10000
```
