### ISSUE TITLE
Can't project any extra columns when using extract method

### ISSUE THREAD

**Issue by anshjain18** [cube-js/cube#7727]
**Failed SQL**
select b2c_orders, extract(day from time) from product_revenue 

**Logical Plan**
Can'e generate explain plan

**Version:**
0.34.50

**Additional context**
1. Here product_revenue is a cube, 'time' is the time dimension, b2c_orders is a measure
2. Error is: "Can't detect Cube query and it may be not supported yet. Please check logs for additional information."

**Comment by igorlukanin** [comment]
Hi @anshjain18 👋 

I'm trying to reproduce this with 0.34.56 and I can't.

My data model:
```yaml
cubes:
  - name: extract_sql
    sql: >
      SELECT 123 AS value, '2023-01-01'::TIMESTAMP AS time UNION ALL
      SELECT 123 AS value, '2023-01-02'::TIMESTAMP AS time UNION ALL
      SELECT 123 AS value, '2023-01-03'::TIMESTAMP AS time UNION ALL
      SELECT 123 AS value, '2023-01-04'::TIMESTAMP AS time UNION ALL
      SELECT 123 AS value, '2023-01-05'::TIMESTAMP AS time

    dimensions:
      - name: time
        sql: time
        type: time

    measures:
      - name: sum
        sql: value
        type: sum
```

My SQL queries:
```bash
remaining-powersville_dev-igor-68ca1f70=> select sum, extract(day from time) from extract_sql;
 sum | datepart(Utf8("DAY"),extract_sql.time) 
-----+----------------------------------------
 123 |                                      1
 123 |                                      2
 123 |                                      3
 123 |                                      4
 123 |                                      5
(5 rows)

remaining-powersville_dev-igor-68ca1f70=> select sum, extract(week from time) from extract_sql;
 sum | datepart(Utf8("WEEK"),extract_sql.time) 
-----+-----------------------------------------
 123 |                                      52
 492 |                                       1
(2 rows)
```

If you can provide a reproducible example, it would greatly help.
