### ISSUE TITLE
Cannot pre-aggregate rolling measure

### ISSUE THREAD

**Issue by naerymdan** [cube-js/cube#7730]
**Describe the bug**
Trying to pre-aggregate a rolling_window measure give the error ` Error: Time series queries without dateRange aren't supported at BaseTimeDimension.timeSeries... `

**To Reproduce**
Create a measure with a rolling_window with a trailing start, create a pre-aggregation for it.

**Expected behavior**
I expect the pre-aggregation to function correctly.

**Minimally reproducible Cube Schema**

```javascript
cube(`session`, {
  sql_table: `test_db`,
  data_source: `default`,
  measures: {
    weeklyCount: {
      sql: `id`,
      type: `count`,
      rollingWindow: {
          leading: `1 week`,
          offset: `start`,
        },
    },
  },
  dimensions: {
    created_at: {
      sql: `${CUBE}."created_at"`,
      type: `time`
    }
  },
  preAggregations: {
    main: {
      measures: [session.weeklyCount],
      timeDimension: session.created_at,
      granularity: `day`
    }
  }
});
```

**Version:**
0.34.50

**Additional context**
Using PostgreSQL, but might be the same issue as #6813 who is using MS SQL

**Comment by igorlukanin** [comment]
I've tried to build the pre-aggregation from the following data model on v0.35.18 with Postgres, and it worked for me:

```javascript
cube(`session`, {
  sql: `
    SELECT 1 AS id, '2024-01-01T00:00:00.000Z' AS created_at UNION ALL
    SELECT 2 AS id, '2024-01-02T00:00:00.000Z' AS created_at UNION ALL
    SELECT 3 AS id, '2024-01-03T00:00:00.000Z' AS created_at
  `,
  data_source: `default`,
  measures: {
    weeklyCount: {
      sql: `id`,
      type: `count`,
      rollingWindow: {
          leading: `1 week`,
          offset: `start`,
        },
    },
  },
  dimensions: {
    created_at: {
      sql: `${CUBE}."created_at"`,
      type: `time`
    }
  },
  preAggregations: {
    main: {
      measures: [session.weeklyCount],
      timeDimension: session.created_at,
      granularity: `day`
    }
  }
});
```

<img width="1392" alt="Screenshot 2024-04-17 at 19 19 59" src="https://github.com/cube-js/cube/assets/3852894/02d74e9d-b58f-48a4-a815-c54ded7e7639">
<img width="1392" alt="Screenshot 2024-04-17 at 19 20 03" src="https://github.com/cube-js/cube/assets/3852894/0bdbd806-d791-4c5f-8b0e-8094114289de">

Could you please upgrade to the latest version and double-check again?

**Comment by igorlukanin** [comment]
Closing this issue due to inactivity and lack of a reproduction. Please feel free to reopen.

**Comment by nbphuoc** [comment]
I experience this issue too. Using `count_distinct_approx` and `count` works fine, but using `count_distinct` results in the mentioned error.

**Comment by alrolorojas** [comment]
Same thing for me as well!

**Comment by igorlukanin** [comment]
> using count_distinct results in the mentioned error

@nbphuoc What is the "mentioned error," exactly? Can you quote?

If you're referring to `Error: Time series queries without dateRange aren't supported...`, then please double-check that you're specifying date range in your query. Copying and pasting your query here would also help.

**Comment by igorlukanin** [comment]
As a workaround, I can maybe recommend using `count_distinct_approx` with Postgres HLL extension: https://cube.dev/docs/product/configuration/data-sources/postgres#count_distinct_approx

**Comment by nbphuoc** [comment]
> As a workaround, I can maybe recommend using `count_distinct_approx` with Postgres HLL extension: https://cube.dev/docs/product/configuration/data-sources/postgres#count_distinct_approx

I would love to use `count_distinct_approx`, but unfortunately, Cube.js doesn't support `count_distinct_approx` for [Redshift](https://cube.dev/docs/product/configuration/data-sources/aws-redshift#count_distinct_approx) pre-aggregation, even though [Redshift supports HLL](https://docs.aws.amazon.com/redshift/latest/dg/r_HLL_function.html) itself. Will this feature be added soon?

**Comment by igorlukanin** [comment]
@nbphuoc Please track this one: https://github.com/cube-js/cube/issues/8510

**Comment by igorlukanin** [comment]
Still reproduces on Cube v0.36.7, same behavior as reported:

<img width="1392" alt="Screenshot 2024-10-08 at 23 47 18" src="https://github.com/user-attachments/assets/bd42dba1-bbc7-4fbf-b373-860836c653d1">

**Comment by mjkanji** [comment]
@igorlukanin Any updates on this?

I used the example you had [in this comment](https://github.com/cube-js/cube/issues/7730#issuecomment-2061809220) and while setting the measure type of `count_distinct` allows the query to be run (if I set a filter on `week` with a specific date range), but I get a message saying the query was not accelerated with a pre-aggregation. If I change it back to `count`, then it works as expected.

Here's the code:

```yaml
cubes:
  - name: session
    sql: >
      SELECT 1 AS id, '2024-12-01T00:00:00.000Z' AS created_at UNION ALL
      SELECT 2 AS id, '2024-12-02T00:00:00.000Z' AS created_at UNION ALL
      SELECT 3 AS id, '2024-12-03T00:00:00.000Z' AS created_at
    
    data_source: default
    dimensions:
      - name: created_at
        sql: "{CUBE}.created_at"
        type: time
    
    measures:
      - name: weekly_count
        sql: id
        type: count_distinct
        rolling_window:
          leading: 1 week
          offset: start
    
    pre_aggregations:
      - name: main
        measures:
          - session.weekly_count
        timeDimension: session.created_at
        granularity: day
```
