### ISSUE TITLE
Cube Store Router Docker Image is not working

### ISSUE THREAD

**Issue by muhammadumerjaved** [cube-js/cube#7772]
**Describe the bug**
Currently, I am using this documentation link for creating workers and cube store 

[https://cube.dev/docs/product/caching/running-in-production#scaling](https://cube.dev/docs/product/caching/running-in-production#scaling)

```
version: '2.2'
services:

  cubestore:
    image: cubejs/cubestore:v0.34.5
    restart: unless-stopped
    environment:
      - CUBESTORE_SERVER_NAME=cubestore:9999
      - CUBESTORE_META_PORT=9999
      - CUBESTORE_WORKERS=cube-refresh-worker:9001
      - CUBESTORE_REMOTE_DIR=/cube/data
    volumes:
      - .cubestore:/cube/data

  cube:
    image: cubejs/cube:v0.34.5
    restart: unless-stopped
    ports:
      - 4001:4000
      - 15432:15432
    volumes:
      - ./analytics:/cube/conf
    env_file:
      - .env
    environment:
      - CUBEJS_API_SECRET=${CUBEJS_API_SECRET}
      - NODE_ENV=${NODE_ENV}
      - CUBEJS_CUBESTORE_HOST=cubestore
      - CUBEJS_DB_HOST=${CUBEJS_DB_HOST}
      - CUBEJS_DB_NAME=${CUBEJS_DB_NAME}
      - CUBEJS_DB_PASS=${CUBEJS_DB_PASS}
      - CUBEJS_DB_PORT=${CUBEJS_DB_PORT}
      - CUBEJS_DB_TYPE=${CUBEJS_DB_TYPE}
      - CUBEJS_DB_USER=${CUBEJS_DB_USER}
      - CUBEJS_REDIS_URL=${CUBEJS_REDIS_URL}
      - CUBEJS_LOG_LEVEL=${CUBEJS_LOG_LEVEL}
      - CUBEJS_DEV_MODE=${CUBEJS_DEV_MODE}
      - CUBEJS_DEFAULT_API_SCOPES=${CUBEJS_DEFAULT_API_SCOPES}
      - CUBEJS_DB_SSL=false
      # - CUBEJS_ROLLUP_ONLY=true
    links:
      - cubestore:cubestore
      - redis:redis
    depends_on:
      - cube-refresh-worker
      - cubestore
      - redis
  cube-refresh-worker:
    image: cubejs/cubestore:v0.34.5
    restart: unless-stopped
    volumes:
      - .cubestore:/cube/data
    env_file:
      - .env
    environment:
      - CUBESTORE_SERVER_NAME=cubestore_worker_2:9001
      - CUBESTORE_WORKER_PORT=9001
      - CUBESTORE_META_ADDR=cubestore:9999
      - CUBESTORE_WORKERS=cube-refresh-worker:9001
      - CUBESTORE_REMOTE_DIR=/cube/data
      # - CUBEJS_ROLLUP_ONLY=true
    links:
      - cubestore:cubestore
      - redis:redis
    depends_on:
      - cubestore
      - redis

  redis:
    image: 'redis:6.0'
    restart: unless-stopped
    ports:
      - 6379:6379
```

The cube store image is exiting with status `Error 132`

**Version:**
[e.g. v0.34.5]

Some one please guide me how to resolve this error
