### ISSUE TITLE
Error: missing FROM-clause entry for table

### ISSUE THREAD

**Issue by wasd171** [cube-js/cube#7803]
**Describe the bug**
In some circumstances it is not possible to use measures with filters

**To Reproduce**
1. Create this minimal Cube model:
<details>
<summary>Show model</summary>

```yaml
cubes:
  - name: "dev_applications"
    sql: >
      select 1 as application_id, true as is_accepted, 1 as user_id
      union all
      select 2 as application_id, false as is_accepted, 2 as user_id

    dimensions:
      - name: application_id
        sql: application_id
        type: number
        primary_key: true

      - name: user_id
        sql: user_id
        type: number

    joins:
      - name: dev_users
        relationship: many_to_one
        sql: "{CUBE}.user_id = {dev_users.user_id}"
    
    measures:
      - name: total_count
        type: count
        sql: application_id

      - name: accepted_count
        type: count
        sql: is_accepted
        filters:
          - sql: "{CUBE}.is_accepted"

  - name: "dev_purchases"
    sql: >
      select 1 as purchase_id, 1 as user_id
      union all
      select 2 as purchase_id, 1 as user_id

    dimensions:
      - name: purchase_id
        sql: purchase_id
        type: number
        primary_key: true

      - name: user_id
        sql: user_id
        type: number

    joins:
      - name: dev_users
        relationship: many_to_one
        sql: "{CUBE}.user_id = {dev_users.user_id}"

    measures:
      - name: total_count
        type: count
        sql: purchase_id

  - name: "dev_users"
    sql: >
      select 1 as user_id
      union all
      select 2 as user_id

    dimensions:
      - name: user_id
        sql: user_id
        type: number
        primary_key: true

    joins:
      - name: dev_applications
        relationship: one_to_many
        sql: "{CUBE}.user_id = {dev_applications.user_id}"

      - name: dev_purchases
        relationship: one_to_many
        sql: "{CUBE}.user_id = {dev_purchases.user_id}"

views:
  - name: view_users
    public: true
 
    cubes:
      - join_path: dev_users
        includes:
          - user_id

      - join_path: "dev_users.dev_applications"
        alias: applications
        prefix: true
        includes:
          - total_count
          - accepted_count

      - join_path: "dev_users.dev_purchases"
        alias: purchases
        prefix: true
        includes:
          - total_count
```
</details>

2. Try a few queries that work fine

`applications_total_count` + `applications_accepted_count`
```json
{
  "limit": 5000,
  "measures": [
    "view_users.applications_total_count",
    "view_users.applications_accepted_count"
  ],
  "dimensions": [
    "view_users.user_id"
  ],
  "timeDimensions": [],
  "order": {
    "view_users.applications_total_count": "desc"
  }
}
```
![SCR-20240222-qmdm](https://github.com/cube-js/cube/assets/8266564/e3937097-502b-4fd0-922b-3162e92b8ca8)

`applications_total_count` + `purchases_total_count`
```json
{
  "limit": 5000,
  "measures": [
    "view_users.applications_total_count",
    "view_users.purchases_total_count"
  ],
  "dimensions": [
    "view_users.user_id"
  ],
  "order": {
    "view_users.applications_total_count": "desc"
  }
}
```
![SCR-20240222-qmod](https://github.com/cube-js/cube/assets/8266564/5836e2e1-9de6-4fc1-9198-4eb328b6b2cc)

3. Try to combine these queries and see a `missing FROM-clause entry for table "dev_purchases"` error
```json
{
  "limit": 5000,
  "measures": [
    "view_users.purchases_total_count",
    "view_users.applications_accepted_count"
  ],
  "dimensions": [
    "view_users.user_id"
  ],
  "order": {
    "view_users.applications_total_count": "desc"
  }
}
```
![SCR-20240222-qmsj](https://github.com/cube-js/cube/assets/8266564/62428085-fa27-4d9e-9d0a-e1b3ec51da97)

And indeed, generated SQL does not specify the table `"dev_purchases"`

<details>
<summary>Show generated SQL</summary>

```sql
SELECT
  q_0."view_users__user_id",
  count("dev_purchases".purchase_id) "view_users__purchases_total_count",
  "dev_applications__accepted_count" "view_users__applications_accepted_count"
FROM
  (
    SELECT
      "keys"."view_users__user_id",
      count(
        CASE
          WHEN (
            "dev_applications_key__dev_applications".is_accepted
          ) THEN "dev_applications_key__dev_applications".is_accepted
        END
      ) "dev_applications__accepted_count"
    FROM
      (
        SELECT
          DISTINCT "dev_applications_key__dev_users".user_id "view_users__user_id",
          "dev_applications_key__dev_applications".application_id "dev_applications__application_id"
        FROM
          (
            select
              1 as user_id
            union all
            select
              2 as user_id
          ) AS "dev_applications_key__dev_users"
          LEFT JOIN (
            select
              1 as purchase_id,
              1 as user_id
            union all
            select
              2 as purchase_id,
              1 as user_id
          ) AS "dev_applications_key__dev_purchases" ON "dev_applications_key__dev_users".user_id = "dev_applications_key__dev_purchases".user_id
          LEFT JOIN (
            select
              1 as application_id,
              true as is_accepted,
              1 as user_id
            union all
            select
              2 as application_id,
              false as is_accepted,
              2 as user_id
          ) AS "dev_applications_key__dev_applications" ON "dev_applications_key__dev_users".user_id = "dev_applications_key__dev_applications".user_id
      ) AS "keys"
      LEFT JOIN (
        select
          1 as application_id,
          true as is_accepted,
          1 as user_id
        union all
        select
          2 as application_id,
          false as is_accepted,
          2 as user_id
      ) AS "dev_applications_key__dev_applications" ON "keys"."dev_applications__application_id" = "dev_applications_key__dev_applications".application_id
    GROUP BY
      1
  ) as q_0
LIMIT
  5000
```

</details>

**Expected behavior**
It is possible to combine measures defined on different cubes that contain filters

**Version:**
Was able to reproduce it on `v0.34.50` and `v0.34.56`

**Comment by igorlukanin** [comment]
Hi @wasd171 👋 

I see that you have both `dev_applications` → `dev_users` and `dev_users` → `dev_applications` joins defined. Same with `dev_purchases`. You don't need to have joins in both directions, one direction is enough. Could you please try to remove unnecessary ones and see if anything changes?

**Comment by wasd171** [comment]
Hi @igorlukanin 

I've removed the joins from the `dev_user` side to get the following schema:

<details>
<summary>Show schema</summary>

```yaml
cubes:
  - name: "dev_applications"
    sql: >
      select 1 as application_id, true as is_accepted, 1 as user_id
      union all
      select 2 as application_id, false as is_accepted, 2 as user_id

    dimensions:
      - name: application_id
        sql: application_id
        type: number
        primary_key: true

      - name: user_id
        sql: user_id
        type: number

    joins:
      - name: dev_users
        relationship: many_to_one
        sql: "{CUBE}.user_id = {dev_users.user_id}"
    
    measures:
      - name: total_count
        type: count
        sql: application_id

      - name: accepted_count
        type: count
        sql: is_accepted
        filters:
          - sql: "{CUBE}.is_accepted"

  - name: "dev_purchases"
    sql: >
      select 1 as purchase_id, 1 as user_id
      union all
      select 2 as purchase_id, 1 as user_id

    dimensions:
      - name: purchase_id
        sql: purchase_id
        type: number
        primary_key: true

      - name: user_id
        sql: user_id
        type: number

    joins:
      - name: dev_users
        relationship: many_to_one
        sql: "{CUBE}.user_id = {dev_users.user_id}"

    measures:
      - name: total_count
        type: count
        sql: purchase_id

  - name: "dev_users"
    sql: >
      select 1 as user_id
      union all
      select 2 as user_id

    dimensions:
      - name: user_id
        sql: user_id
        type: number
        primary_key: true

views:
  - name: view_users
    public: true
 
    cubes:
      - join_path: dev_users
        includes:
          - user_id

      - join_path: "dev_users.dev_applications"
        alias: applications
        prefix: true
        includes:
          - total_count
          - accepted_count

      - join_path: "dev_users.dev_purchases"
        alias: purchases
        prefix: true
        includes:
          - total_count

```
</details>

But now I cannot query even the fields that worked before
```json
{
  "limit": 5000,
  "measures": [
    "view_users.purchases_total_count",
    "view_users.applications_total_count"
  ],
  "dimensions": [
    "view_users.user_id"
  ],
  "order": {
    "view_users.applications_total_count": "desc"
  }
}
```
![SCR-20240223-nhgm](https://github.com/cube-js/cube/assets/8266564/252a5bad-dce4-423a-b94f-f6693706a46c)
Logs:
```
UserError: 56fab030-f692-44ed-98e3-d0a2f61c9503-span-1 (8ms)
--
{
  "limit": 5000,
  "measures": [
    "view_users.purchases_total_count",
    "view_users.applications_total_count"
  ],
  "dimensions": [
    "view_users.user_id"
  ],
  "order": {
    "view_users.applications_total_count": "desc"
  }
}
--
{}
Can't find join path to join 'dev_users,dev_purchases', 'dev_users,dev_applications', 'dev_users'
Refresh Scheduler Error: scheduler-2fcb6236-4db3-42ba-956c-dc9facb73e75
{
  "securityContext": {}
}
Error: Can't find join path to join 'dev_users,dev_applications', 'dev_users'
    at JoinGraph.buildJoin (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/JoinGraph.js:112:15)
    at PostgresQuery.initFromOptions (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:244:32)
    at new BaseQuery (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:96:10)
    at new PostgresQuery (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/PostgresQuery.ts:21:1)
    at createQuery (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/QueryBuilder.js:60:10)
    at CompilerApi.createQuery (/cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:203:23)
    at CompilerApi.createQueryByDataSource (/cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:199:17)
    at CompilerApi.getSqlGenerator (/cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:123:24)
    at CompilerApi.getSql (/cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:149:41)
    at /cube/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:360:26
    at async Promise.all (index 0)
    at /cube/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:347:7
    at async Promise.all (index 3)
    at RefreshScheduler.refreshCubesRefreshKey (/cube/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:340:5)
    at async Promise.all (index 0)
    at RefreshScheduler.runScheduledRefresh (/cube/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:285:9)
```

This happens on `v0.34.56`
