### ISSUE TITLE
bug: incorrect CASE WHEN generated during ungrouped filtered count  

### ISSUE THREAD

**Issue by adamstruck** [cube-js/cube#7858]
**Describe the bug**

This is related to the changes https://github.com/cube-js/cube/pull/7853.

Distinct count measures always return `1` due to how the `CASE WHEN` statements are generated. 

The new case statement of the form `CASE WHEN (<dimension>) IS NOT NULL THEN 1 END` produces the wrong result when it is included in a `COUNT(DISTINCT <dimension>)`.

Note: the example below is a truncated excerpt from an `EXPLAIN` query against the SQL API to highlight the problematic generated SQL.

```
SELECT 
  "case_when_nexus_" "nexus__utilizati",
  "count_distinct_n" "nexus__utilizati_1" 
FROM (
  SELECT
    CASE WHEN "nexus__utilizations"."point__in__time_" THEN ? ELSE ? END "case_when_nexus_",
    COUNT(DISTINCT "nexus__utilizations"."utilizations__un") "count_distinct_n" 
  FROM (
    SELECT
      CASE WHEN ("utilizations".primary_key) IS NOT NULL THEN 1 END "utilizations__to",
      CASE WHEN ("utilizations".entity_id) IS NOT NULL THEN 1 END "utilizations__to_1",
      CASE WHEN ("utilizations".observation_id) IS NOT NULL THEN 1 END "utilizations__un",
      "utilizations".window_end_date "utilizations__wi",
      "utilizations".window_start_date "utilizations__wi_2",
      "point__in__time__hvhn".is_hvhn "point__in__time_"
    FROM
      yellow.metric_speed_train__utilizations__v1 AS "utilizations"
      LEFT JOIN yellow.data_science__member_feature_bank__is_hvhn__v1 AS "point__in__time__hvhn" ON "utilizations".entity_id = "point__in__time__hvhn".entity_id and "utilizations".window_end_date BETWEEN "point__in__time__hvhn".start_date AND "point__in__time__hvhn".end_date
    WHERE 
      (
        (
          ("utilizations".window_end_date >= from_iso8601_timestamp('2023-03-02T00:00:00.000Z'))
          AND ("utilizations".window_end_date < from_iso8601_timestamp('2024-03-01T00:00:00.000Z'))
        )
      )
    LIMIT 10000
  ) AS "nexus__utilizations" 
) AS "nexus__utilizations" 
```

**Version:**
0.34.59

**Additional context**

I have `CUBESQL_SQL_PUSH_DOWN=true` enabled and am running queries against AWS Athena.

**Comment by adamstruck** [comment]
The input SQL query

```
SELECT
  (CASE WHEN nexus__utilizations.point__in__time__hvhn__is_hvhn  THEN 'Yes' ELSE 'No' END) AS "nexus__utilizations.point__in__time__hvhn__is_hvhn",
  COUNT(DISTINCT nexus__utilizations.utilizations__unique_observations ) AS "nexus__utilizations.utilizations__unique_observations"
FROM
  nexus__utilizations AS nexus__utilizations
WHERE
  (
    ( nexus__utilizations.utilizations__window_end_date  ) >= ((SELECT (DATE_TRUNC('day', CURRENT_TIMESTAMP) + (-364 || ' day')::INTERVAL))) 
    AND ( nexus__utilizations.utilizations__window_end_date  ) < ((SELECT ((DATE_TRUNC('day', CURRENT_TIMESTAMP) + (-364 || ' day')::INTERVAL) + (365 || ' day')::INTERVAL)))
  )
GROUP BY
    1
ORDER BY
    1
```

The `CASE` statement in the select seems to trigger the problem.

**Comment by paveltiunov** [comment]
@adamstruck Thanks for bringing this up! Could you please share your cube definition?

**Comment by adamstruck** [comment]
Sure, here you go:

```
views:
- name: nexus__utilizations
  cubes:
  - join_path: utilizations
    includes:
    - name: total_observations
      alias: utilizations__total_observations
    - name: unique_observations
      alias: utilizations__unique_observations
    - name: window_start_date
      alias: utilizations__window_start_date
    - name: window_end_date
      alias: utilizations__window_end_date
    - name: primary_key
      alias: utilizations__primary_key
    - name: observation_id
      alias: utilizations__observation_id

  - join_path: utilizations.point__in__time__hvhn
    includes:
    - name: is_hvhn
      alias: point__in__time__hvhn__is_hvhn

cubes:
- name: utilizations
  sql_table: yellow.metric_speed_train__utilizations__v1
  joins:
  - name: point__in__time__hvhn
    relationship: one_to_one
    sql: '{CUBE}.entity_id = {point__in__time__hvhn}.entity_id and {CUBE}.window_end_date BETWEEN {point__in__time__hvhn}.start_date AND {point__in__time__hvhn}.end_date'
  measures:
  - name: unique_observations
    sql: observation_id
    type: countDistinct
  - name: total_observations
    sql: primary_key
    type: countDistinct
  dimensions:
  - name: primary_key
    sql: primary_key
    type: string
    primary_key: true
  - name: observation_id
    sql: observation_id
    type: string
  - name: entity_id
    sql: entity_id
    type: string
  - name: window_start_date
    sql: window_start_date
    type: time
  - name: window_end_date
    sql: window_end_date
    type: time

- name: high__value__high__needs
  sql_table: yellow.data_science__member_feature_bank__is_hvhn__v1
  dimensions:
  - name: entity_id
    sql: entity_id
    type: string
  - name: is_hvhn
    sql: is_hvhn
    type: boolean
  - name: start_date
    sql: start_date
    type: time
  - name: end_date
    sql: end_date
    type: time
  - name: primary_key
    sql: CONCAT({CUBE}.entity_id, CAST({CUBE}.start_date AS VARCHAR), CAST({CUBE}.end_date AS VARCHAR))
    type: string
    primary_key: true

- name: point__in__time__hvhn
  extends: high__value__high__needs
```
