### ISSUE TITLE
core in production having the cubestore unreachable

### ISSUE THREAD

**Issue by Namec999** [cube-js/cube#8061]
hello All,

trying to deploy core in production using the and the cubestore

here is my docker compose file

and my .env

whats wrong ???? because i have access to the API and can list the members (dimensions, measures, ...) but when executing a query got this error : Error: Error: connect ECONNREFUSED 127.0.0.1:3030

docker compose : 
```yaml
version: "2.2"
services:
  cubestore:
    image: cubejs/cubestore:latest
    #-non-avx
    ports:
      - 3030:3030
    environment:
      - CUBESTORE_REMOTE_DIR=/cube/data
    volumes:
      - C:/66/cubeDocker/data:/cube/data
 
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
    environment:
      - CUBEJS_CUBESTORE_HOST=localhost
      - CUBEJS_CUBESTORE_PORT=3030
      - CUBEJS_DB_TYPE=clickhouse
      - CUBEJS_DB_HOST=192.168.100.2
      - CUBEJS_DB_PORT=18123
      - CUBEJS_DB_NAME=default
      - CUBEJS_DB_USER=username
      - CUBEJS_DB_PASS=password
      - CUBEJS_API_SECRET=87896xxxxxxxxxxxxxxxxxxxx-017
      - CUBEJS_WEB_SOCKETS=true
      - NODE_ENV=production
    depends_on:
      - cubestore
    links:
      - cubestore
    volumes:
      - C:/66/cubeDocker:/cube/conf
```

and my .env
```dotenv
CUBEJS_DB_HOST=host.docker.internal
CUBEJS_DB_PORT=18123
CUBEJS_DB_NAME=default
CUBEJS_DB_USER=username
CUBEJS_DB_PASS=password
CUBEJS_DB_TYPE=clickhouse
CUBEJS_API_SECRET=87896xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx7
CUBEJS_EXTERNAL_DEFAULT=true
CUBEJS_SCHEDULED_REFRESH_DEFAULT=true
CUBEJS_DEV_MODE=false
NODE_ENV=production
CUBEJS_SCHEMA_PATH=model
CUBEJS_CUBESTORE_HOST=host.docker.internal
CUBEJS_CUBESTORE_PORT=3030
```
