### ISSUE TITLE
Sample for Cubejs QuestDB integration is out dated

### ISSUE THREAD

**Issue by truedat101** [cube-js/cube#8177]
**Describe the bug**
https://cube.dev/blog/time-series-data-analytics-with-questdb

is a nice tutorial, but it is a few years old, and using the docker example with "latest" builds is not the right mixture of versions for cubejs and questdb.  Older versions can match the example, and the latest won't run successfully.

**To Reproduce**

Run the steps in https://cube.dev/blog/time-series-data-analytics-with-questdb

Observe the failure to be able to complete the tutorial

**Expected behavior**

Steps should match exactly https://cube.dev/blog/time-series-data-analytics-with-questdb

My recommendation is to update the blog post, or change the blog post to use the exact supported versions.

This combination works:

image: "cubejs/cube:v0.31.69"
image: "questdb/questdb:6.7"

**Version:**
latest

**Additional context**
na

**Comment by igorlukanin** [comment]
Hi @truedat101 👋 

> Observe the failure to be able to complete the tutorial

Could you please provide more details here? What exactly did not work for you?

**Comment by truedat101** [comment]
Sorry for the late reply, without going to deep on why this doesn't work, following the blog post (instead of some README with up to date instructions), the tell is this line the docker compose file mentioned in the example.  This example calls for the latest versions of the docker images.  This might be an easy way to document the demo, but if you run latest questdb and latest cubejs, the example in the blog post can't get through the "cube data model" portion.  Something wrong in the API.  Can't say for sure, but I couldn't follow the example through this part.  It only worked when I went back to older versions of quest and cube.js.  So by worked, I mean, I can complete the steps in the examples.

```
version: "2.2"

services: 
  cube: 
    environment: 
      - CUBEJS_DEV_MODE=true
    image: "cubejs/cube:latest"
    ports: 
      - "4000:4000"
    volumes: 
      - ".:/cube/conf"
  questdb: 
    container_name: questdb
    hostname: questdb
    image: "questdb/questdb:latest"
    ports: 
      - "9000:9000"
      - "8812:8812"
```
