### ISSUE TITLE
Network error: Corrupted message received. Please check your worker and meta connection environment variables.

### ISSUE THREAD

**Issue by Pranayagaram1** [cube-js/cube#8414]
Hi All,

Below is my Docker Compose file, I am trying to run route and worker containers on the Server.

The router can't connect to Worker Containers.

Error: Network error: Corrupted message received. Please check your worker and meta connection environment variables.

```yaml
version: "2.2"
services:
  cubestore_router:
    container_name: cubestore_router
    restart: always
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_SERVER_NAME=cubestore_router
      - CUBESTORE_META_PORT=9999
      - CUBESTORE_WORKERS=cubestore_worker_1:9001,cubestore_worker_2:9002
      - CUBESTORE_S3_BUCKET=pf-XXXXXXX-uat
      - CUBESTORE_S3_REGION=us-east-2
      - CUBESTORE_AWS_ACCESS_KEY_ID=AKIXXXXXXXXXXXXXXLXT
      - CUBESTORE_AWS_SECRET_ACCESS_KEY=oc4EgE9XXXXXXXXXXXXXXXXXXXXXXXXXXXvz2J
    ports:
      - "9999:9999"

  cubestore_worker_1:
    container_name: cubestore_worker_1
    restart: always
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_SERVER_NAME=cubestore_worker_1
      - CUBESTORE_WORKER_PORT=9001
      - CUBESTORE_META_ADDR=cubestore_router:9999
      - CUBESTORE_WORKERS=cubestore_worker_1:9001,cubestore_worker_2:9002
      - CUBESTORE_S3_BUCKET=pf-XXXXXXX-uat
      - CUBESTORE_S3_REGION=us-east-2
      - CUBESTORE_AWS_ACCESS_KEY_ID=AKIXXXXXXXXXXXXXXLXT
      - CUBESTORE_AWS_SECRET_ACCESS_KEY=oc4EgE9XXXXXXXXXXXXXXXXXXXXXXXXXXXvz2J
    depends_on:
      - cubestore_router
    ports:
      - "9001:9001"

  cubestore_worker_2:
    container_name: cubestore_worker_2
    restart: always
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_SERVER_NAME=cubestore_worker_2
      - CUBESTORE_WORKER_PORT=9002
      - CUBESTORE_META_ADDR=cubestore_router:9999
      - CUBESTORE_WORKERS=cubestore_worker_1:9001,cubestore_worker_2:9002
      - CUBESTORE_S3_BUCKET=pf-XXXXXXX-uat
      - CUBESTORE_S3_REGION=us-east-2
      - CUBESTORE_AWS_ACCESS_KEY_ID=AKIXXXXXXXXXXXXXXXXXXF6LXT
      - CUBESTORE_AWS_SECRET_ACCESS_KEY=ocXXXXXXXXXXXXXXXXXXXXXXXXXXXXok
    depends_on:
      - cubestore_router
    ports:
      - "9002:9002"
```
