### ISSUE TITLE
Preaggregation not working in case of CountDistinct 

### ISSUE THREAD

**Issue by GitMedic** [cube-js/cube#8468]
I have a measure in my cube which is as below
```yaml
      - name: count_op_number
        type: countDistinct
        sql: "{CUBE}.`_opNumber`"
        title: "OP Count" 
```  
I have created a Preaggregration using the below code 
```yaml
       - name: op_count
        measures:
          - count_op_number
        time_dimension: invoice_date
        granularity: day
```

And my query params like the below code . 

```json
{"ungrouped":false,"limit":10,"offset":0,"measures":["users.count_op_number"],"timeDimensions":[{"dimension":"users.invoice_date","dateRange":["2023-07-15","2024-07-15"]}]}  ,
````
 My query is not accelerated using the preaggregration defined , Why is it so ??
