### ISSUE TITLE
Dimensions with missing `type`  in child cubes don't break data model compilation

### ISSUE THREAD

**Issue by igorlukanin** [cube-js/cube#8609]
**Describe the bug**
If a dimension definition doesn't have the `type` parameter, the data model would not compile, which is expected:
```yaml
# THIS WOULD NOT COMPILE
cubes:
  - name: base_cube
    sql_table: foo

    measures:
      - name: count
        type: count

    dimensions:
      - name: baz
        sql: baz
        # NO TYPE HERE
```

However, if this dimension is a child cube that `extends` another one, the data model would compile:
```yaml
# THIS WOULD COMPILE BUT IT SHOULD NOT
cubes:
  - name: base_cube
    sql_table: foo

    measures:
      - name: count
        type: count

  - name: child_cube
    extends: base_cube

    dimensions:
      - name: bar
        sql: bar
        # NO TYPE HERE
```

The dimension would appear in `/meta` without any type:
```json
      "dimensions": [
        {
          "name": "child_cube.bar",
          "title": "Child Cube Bar",
          "shortTitle": "Bar",
          "suggestFilterValues": true,
          "isVisible": true,
          "public": true,
          "primaryKey": false
        }
      ],
```

Apparently, it would work with the REST API without issues.

However, running any queries against the SQL API, e.g., `\d`, would result in the following error:
```
ERROR:  missing field `type` at line 1 column 12227
```

**To Reproduce**
See above.

**Expected behavior**
Dimensions without `type` never compile.

**Version:**
0.35.73
