### ISSUE TITLE
SQL TIME type not recognized

### ISSUE THREAD

**Issue by lara-bellatin** [cube-js/cube#8639]
**Describe the bug**
I need to cast a timestamp value into one of type time, as I only need the hours:minutes:seconds part of it. It works when I try it directly on my data using `created_at::TIME` in a SQL query, but errors out in the cube, both as I try to cast the value in the dimension definition and also when querying my cube using SQL.

**To Reproduce**
A. Defining a dimension
1. Create a cube for a table with a timestamp column
2. Define a dimension that casts the timestamp column into a TIME type (`sql: 'timestamp_col::TIME`)
3. Load your cube and see the error

B. Querying a cube
1. Create a cube for a table with a timestamp column
2. Connect to your cube
3. Write a SQL query that casts the timestamp column into a TIME type (`SELECT timestamp_col::TIME FROM table)
4. Run the query and see the error message

**Expected behavior**
I expect to see a column of type TIME produced, like in the image below.
Query used: `SELECT created_at as timestamp_column, created_at::TIME as time_column FROM table`
![CleanShot 2024-08-26 at 3  03 24](https://github.com/user-attachments/assets/bdb557d8-824b-4403-a165-95cb524b9442)

**Screenshots**
Error when trying to query the cube casting a field using `::TIME`:
![CleanShot 2024-08-26 at 3  05 29](https://github.com/user-attachments/assets/a39d51db-a89d-4b23-a516-a1b55211add7)

Error when trying to set a dimension in the cube using `::TIME` either in the sql for the entire cube or for the specific dimension:
![CleanShot 2024-08-26 at 4  00 16@2x](https://github.com/user-attachments/assets/91e5d6db-68f2-46e6-a5b8-360ab470b7ee)

**Version:**
[e.g. 0.4.5]

**Comment by igorlukanin** [comment]
Hi @lara-bellatin 👋 

Would you please try this example? Data model:

```yaml
cubes:
  - name: time
    sql: SELECT '2024-03-02T01:23:45.678Z'::TIMESTAMP AS timestamp

    dimensions:
      - name: timestamp
        sql: timestamp
        type: time

      - name: time
        sql: "(timestamp::TIME)::TEXT"
        type: string
```

The query:

<img width="865" alt="Screenshot 2024-08-29 at 15 33 09" src="https://github.com/user-attachments/assets/aae8b788-fe0b-407b-baf4-18b6d27d6106">

Does this help?
