### ISSUE TITLE
CubeStore Error: No such file or directory

### ISSUE THREAD

**Issue by g-diwakar** [cube-js/cube#8759]
**Describe the bug**
ERROR [cubestore::remotefs::cleanup] <pid:1> error while trying to list local files: No such file or directory (os error 2)
**To Reproduce**
Running the cube store worker, it is throwing the above error. 
I have deployed the cube as instructed here. 

**Expected behavior**

**Screenshots**

**Minimally reproducible Cube Schema**
In case your bug report is data modelling related please put your minimally reproducible Cube Schema here.
You can use selects without tables in order to achieve that as follows.

```javascript
cube(`Orders`, {
  sql: `
  select 1 as id, 100 as amount, 'new' status
  UNION ALL
  select 2 as id, 200 as amount, 'new' status
  UNION ALL
  select 3 as id, 300 as amount, 'processed' status
  UNION ALL
  select 4 as id, 500 as amount, 'processed' status
  UNION ALL
  select 5 as id, 600 as amount, 'shipped' status
  `,
  measures: {
    count: {
      type: `count`,
    },
    totalAmount: {
      sql: `amount`,
      type: `sum`,
    },
    toRemove: {
      type: `count`,
    },
  },
  dimensions: {
    status: {
      sql: `status`,
      type: `string`,
    },
  },
});
```

**Version:**
[e.g. 0.4.5]

**Additional context**

**Comment by igorlukanin** [comment]
Hi @g-diwakar 👋 

> Cube Store : v0.36.0
> Cube Api : v0.35.57

I would strongly advise to only run the same versions for Cube Store and Cube.

> For some reason cube router is refusing the connection request.

I guess this one should be resolved first. I bet there's either some networking misconfiguration. How/where do you deploy Cube? Are you 100% sure its nodes can reach each other?

**Comment by pebabion** [comment]
I'm experiencing this issue as well - after matching the version of cubestore and cube API the errors stopped happening.

**Comment by igorlukanin** [comment]
@pebabion Which one of the two mentioned in the original message? Also, would you mind providing additional details as well?

**Comment by pebabion** [comment]
@igorlukanin the error that is happening for me is in the `cubestore-worker` pod.

```
2024-12-13 02:21:16,666 ERROR [cubestore::remotefs::cleanup] <pid:1> error while trying to list local files: No such file or directory (os error 2)
```

We followed the documentation and got `cubestore` deployed as below.

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: cubestore-router
  name: cubestore-router
  namespace: default
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
spec:
  serviceName: cubestore-router
  selector:
    matchLabels:
      service: cubestore-router
  template:
    metadata:
      labels:
        service: cubestore-router
    spec: # Can't scale cubestore-router without cube cloud, so we'll just use a single replica
      containers:
        - name: cubestore-router
          image: cubejs/cubestore:latest
          env:
            - name: CUBESTORE_META_PORT
              value: "9999"
            - name: CUBESTORE_DATA_DIR
              value: /cube/.cubestore/data
            - name: CUBESTORE_SERVER_NAME
              value: cubestore-router.default.svc.cluster.local:9999
            - name: CUBESTORE_WORKERS
              value: cubestore-workers-0.cubestore-workers:10000,cubestore-workers-1.cubestore-workers:10000,cubestore-workers-2.cubestore-workers:10000,cubestore-workers-3.cubestore-workers:10000,cubestore-workers-4.cubestore-workers:10000
            - name: CUBESTORE_S3_BUCKET
              value: xxxxxxxx
            - name: CUBESTORE_S3_SUB_PATH
              value: "cubestore"
            - name: CUBESTORE_S3_REGION
              value: us-east-2
            - name: CUBESTORE_QUERY_TIMEOUT
              value: "600"
            - name: CUBESTORE_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: cubejs-key
            - name: CUBESTORE_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: cubejs-secret
          ports:
            - containerPort: 9999
          resources:
            requests:
              cpu: 800m
              memory: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: cubestore-workers
  name: cubestore-workers
  namespace: default
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
spec:
  replicas: 5 # If you edit this, make sure to edit the CUBESTORE_WORKERS as well
  serviceName: cubestore-workers
  selector:
    matchLabels:
      service: cubestore-workers
  template:
    metadata:
      labels:
        service: cubestore-workers
    spec:
      containers:
        - name: cubestore-workers
          image: cubejs/cubestore:v0.34.60
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CUBESTORE_META_ADDR
              value: cubestore-router.default.svc.cluster.local:9999
            - name: CUBESTORE_DATA_DIR
              value: /cube/.cubestore/data
              # The $(POD_NAME) is a way of referencing dependent env vars
              # It will resolve to "cubestore-workers-n" where n is the replica number
            - name: CUBESTORE_SERVER_NAME
              value: "$(POD_NAME).cubestore-workers.default.svc.cluster.local:10000"
              # With 3 replicas the POD_NAMEs will be cubestore-workers-0,cubestore-workers-1, and cubestore-workers-2
              # These will then be needed in the CUBESTORE_WORKERS env var as an array
              # We use "cubestore-workers-0.cubestore-workers:10000" as it points to the headless service
              # See also cubestore-router-statefulset.yaml
            - name: CUBESTORE_WORKERS
              value: cubestore-workers-0.cubestore-workers.default.svc.cluster.local:10000,cubestore-workers-1.cubestore-workers.default.svc.cluster.local:10000,cubestore-workers-2.cubestore-workers.default.svc.cluster.local:10000,cubestore-workers-3.cubestore-workers.default.svc.cluster.local:10000,cubestore-workers-4.cubestore-workers.default.svc.cluster.local:10000
            - name: CUBESTORE_WORKER_PORT
              value: "10000"
            - name: CUBESTORE_S3_BUCKET
              value: xxxxxxxxxxx
            - name: CUBESTORE_S3_SUB_PATH
              value: "cubestore"
            - name: CUBESTORE_S3_REGION
              value: us-east-2
            - name: CUBESTORE_QUERY_TIMEOUT
              value: "600"
            - name: CUBESTORE_LOG_LEVEL
              value: "warn"
            - name: CUBESTORE_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: cubejs-key
            - name: CUBESTORE_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: cubejs-secret
          ports:
            - containerPort: 10000
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
      initContainers:
        - name: init-router
          image: busybox
          command:
            [
              "sh",
              "-c",
              'until nc -vz cubestore-router:9999; do echo "Waiting for router"; sleep 2; done;',
            ]
```
