### ISSUE TITLE
cube store fails to start with CUBESTORE_LOG_LEVEL=error

### ISSUE THREAD

**Issue by Hvitgar** [cube-js/cube#9073]
**Describe the bug**
Local deployments of cubejs fail when CUBESTORE_LOG_LEVEL is set to error or warn. Levels info, debug and trace start sucessfully.

**To Reproduce**
run the docker compose below
```yml
services:
  cube_api:
    image: cubejs/cube:v1.1.11
    ports:
      - 4000:4000
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBESTORE_LOG_LEVEL=error # or warn
```

**Version:**
1.1.11
