### ISSUE TITLE
Invalid PostgreSQL using DISTINCT in many-to-one relationship?

### ISSUE THREAD

**Issue by strfngr** [cube-js/cube#9134]
In an orders cube, I am joining a patients cube with a many-to-one relationship. Running a query on orders joining any dimension/measure from patients results in an SQL error: `syntax error at or near "DISTINCT"`

### **Cubes**

orders:
```
cubes:
  - name: orders
    sql: |
      SELECT o.*, b.is_usage_relevant AS blocker_is_usage_relevant FROM public.hospichef_order o
      LEFT JOIN public.hospichef_orderblocker b
        ON b.id = o.blocker_id
      WHERE o.is_valid
    data_source: default

    joins:
      - name: patients
        sql: "{CUBE}.patient_id = {patients}.user_id"
        relationship: "many_to_one"

    measures:
      - name: count
        type: count

    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true

      - name: patient_id
        sql: patient_id
        type: number

  - name: patients
    sql: |
      SELECT (DISTINCT ON p.id) p.*, s.id AS station_order_relevant_id, s_current.id AS station_current_id
      FROM hospichef_patientdata p
      LEFT JOIN hospichef_patientdata_stations_current s_current ON s_current.patientdata_id = p.id
      LEFT JOIN hospichef_patientdata_stations s ON s.patientdata_id = p.id
    data_source: default

    joins:
      - name: stations
        sql: "{CUBE}.station_order_relevant_id = {stations}.id"
        relationship: many_to_one

    measures:
      - name: count
        type: count

    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true

      - name: user_id
        sql: user_id
        type: number
```

### **Generated SQL**
```
SELECT
  count("orders".id) "orders__count"
FROM
  (
    SELECT
      o.*,
      b.is_usage_relevant AS blocker_is_usage_relevant
    FROM
      public.hospichef_order o
      LEFT JOIN public.hospichef_orderblocker b ON b.id = o.blocker_id
    WHERE
      o.is_valid
  ) AS "orders"
  LEFT JOIN (
    SELECT
      (DISTINCT ON p.id) p.*,
      s.id AS station_order_relevant_id,
      s_current.id AS station_current_id
    FROM
      hospichef_patientdata p
      LEFT JOIN hospichef_patientdata_stations_current s_current ON s_current.patientdata_id = p.id
      LEFT JOIN hospichef_patientdata_stations s ON s.patientdata_id = p.id
  ) AS "patients" ON "orders".patient_id = "patients".user_id
WHERE
  ("patients".id IS NOT NULL)
LIMIT
  10000
```

--> **Moving the opening parenthesis to after "DISTINCT ON" resolves the issue in my query editor**:
```
LEFT JOIN (
    SELECT
      DISTINCT ON (p.id) p.*,
      s.id AS station_order_relevant_id,
      s_current.id AS station_current_id
...
```

### **Version:**
cube: v1.1.16
postgres: 14-alpine
