### ISSUE TITLE
Minio as persistence fails during pre-aggregation

### ISSUE THREAD

**Issue by LeftoversTodayAppAdmin** [cube-js/cube#9206]
**Describe the bug**

When using Minio for storage for pre-aggregation, I am able to see Cube write files to the temp-uploads folder in the Minio bucket but then it fails with the following error from this line of code, and Cube generates lots of copies of the same file in temp-uploads

Line of code emitting the error:
https://github.com/cube-js/cube/blob/7ef628273905d47996b108862a52dde89b9525e3/rust/cubestore/cubestore/src/remotefs/mod.rs#L124

`Error: Error during upload of dev_pre_aggregations.order_main20240928_ookkyqrs_dp11nujr_1jqgh50-0.csv.gz create table: CREATE TABLE dev_pre_aggregations.order_main20240928_ookkyqrs_dp11nujr_1jqgh50 (`order__customfieldsvendoridentifier` varchar(255), `order__updatedat_day` timestamp, `order__count` int) WITH (build_range_end = '2024-09-28T23:59:59.999'): Internal: File temp-uploads/dev_pre_aggregations.order_main20240928_ookkyqrs_dp11nujr_1jqgh50-0.csv.gz can't be listed after upload. Either there's Cube Store cluster misconfiguration, or storage can't provide the required consistency.
`

Minio integration was added here: https://github.com/cube-js/cube/pull/3738
cc: @PieterVanZyl-Dev @paveltiunov 

**To Reproduce**
1. Use the following config in docker:
```yaml
  cubestore_router:
    restart: always
    image: cubejs/cubestore:v1.2.3-non-avx
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001,cubestore_worker_2:10002
      - CUBESTORE_META_PORT=9999
      - CUBESTORE_SERVER_NAME=cubestore_router:9999
      - CUBESTORE_DATA_DIR=/cube/data
      - CUBESTORE_MINIO_SERVER_ENDPOINT=http://leftoverstoday-dev-01:9000
      - CUBESTORE_MINIO_BUCKET=cube
      - CUBESTORE_MINIO_REGION=''
      - CUBESTORE_MINIO_ACCESS_KEY_ID=minio
      - CUBESTORE_MINIO_SECRET_ACCESS_KEY=<KEY>
    volumes:
      - .cubestore:/cube/data
```
2. Create a pre-aggregation
3. Open the playground and run the query
4. Cube will try to generate the pre-aggregation files
5. The files are created successfully in the Minio bucket under the folder temp-uploads but when it immediately tries to read it again, it fails and creates another copy of the file, repeating indefinitely

**Expected behavior**
The file is created and read successfully

**Screenshots**

![Image](https://github.com/user-attachments/assets/9c89a45b-fb66-4a72-ac0f-c5dab422744b)

**Minimally reproducible Cube Schema**
In case your bug report is data modelling related please put your minimally reproducible Cube Schema here.
You can use selects without tables in order to achieve that as follows.

```yaml
cubes:
  - name: order
    sql_table: vendure.order
    data_source: default

    joins: []

    dimensions:
      - name: id
        sql: id
        type: string
        primary_key: true

      - name: type
        sql: type
        type: string

      - name: code
        sql: code
        type: string

      - name: state
        sql: state
        type: string

      - name: couponcodes
        sql: "{CUBE}.`couponCodes`"
        type: string

      - name: shippingaddress
        sql: "{CUBE}.`shippingAddress`"
        type: string

      - name: billingaddress
        sql: "{CUBE}.`billingAddress`"
        type: string

      - name: currencycode
        sql: "{CUBE}.`currencyCode`"
        type: string

      - name: aggregateorderid
        sql: "{CUBE}.`aggregateOrderId`"
        type: string

      - name: customerid
        sql: "{CUBE}.`customerId`"
        type: string

      - name: taxzoneid
        sql: "{CUBE}.`taxZoneId`"
        type: string

      - name: customfieldstotalWeightLbs
        sql: "{CUBE}.`customFieldsTotalWeightLbs`"
        type: number

      - name: customfieldssavingsDollars
        sql: "{CUBE}.`customFieldsSavingsDollars`"
        type: number

      - name: customfieldsvendoridentifier
        sql: "{CUBE}.`customFieldsVendoridentifier`"
        type: string

      - name: customfieldssnapebt
        sql: "{CUBE}.`customFieldsSnapebt`"
        type: string

      - name: customfieldsdob
        sql: "{CUBE}.`customFieldsDob`"
        type: string

      - name: customfieldsphone
        sql: "{CUBE}.`customFieldsPhone`"
        type: string

      - name: createdat
        sql: "{CUBE}.`createdAt`"
        type: time

      - name: updatedat
        sql: "{CUBE}.`updatedAt`"
        type: time

      - name: orderplacedat
        sql: "{CUBE}.`orderPlacedAt`"
        type: time

    measures:
      - name: count
        type: count

      - name: subtotal
        sql: "{CUBE}.`subTotal`"
        type: sum
      
      - name: weight
        sql: "{CUBE}.`customfieldstotalWeightLbs`"
        type: sum
      
      - name: dollars
        sql: "{CUBE}.`customFieldsSavingsDollars`"
        type: sum

    pre_aggregations:
      # Pre-aggregation definitions go here.
      # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started
      - name: main
        measures:
          - order.count
          - order.weight
          - order.dollars
        dimensions:
          - order.customfieldsvendoridentifier
          - order.state
        refreshKey:
          every: 1 hour
          updateWindow: 3 day
          incremental: true
        partitionGranularity: day
        timeDimension: order.orderplacedat
        granularity: day
```

**Version:**
cubejs/cube:v1.2.3
cubejs/cubestore:v1.2.3-non-avx

**Additional context**
