### ISSUE TITLE
Access policies with arrays in security context

### ISSUE THREAD

**Issue by tagspace** [cube-js/cube#9248]
**Describe the bug**
Can't use array of values for access policy row level filter.

**To Reproduce**

Given the following `access_policy`:

```
cubes:
  - name: customers
    sql_table: public.customers

    access_policy:
      - role: "*"
        row_level:
          filters:
            - member: country
              operator: equals
              values: { securityContext.countries }
...
```

And the following `securityContext`:

```
{
  "countries": [
    "Germany",
    "United States"
  ]
}
```

If I try to query it:

```
{
  "dimensions": [
    "customers.country"
  ],
  "measures": [
    "customers.count"
  ],
  "order": {},
  "timeDimensions": []
}
```

I get error: `Unexpected input during yaml transpiling: null`

**Expected behavior**
Should be possible to filter by multiple values (just like the standard `filter` operator works in cube)

From [docs](https://cube.dev/docs/reference/data-model/data-access-policies): "row filters are configured using the same format as [filters in REST API](https://cube.dev/docs/product/apis-integrations/rest-api/query-format#filters-format) queries, allowing to use the same set of [filter operators](https://cube.dev/docs/product/apis-integrations/rest-api/query-format#filters-operators), e.g., equals, contains, gte, etc."

**Version:**
Cube Cloud (1.2.6)

**Comment by tagspace** [comment]
Turns out this works fine if you change `values` to :
`values: "{ [securityContext.countries] }"`

**Comment by tagspace** [comment]
Thanks @paco-valdez for the suggestion 🙏

**Comment by eshepelyuk** [comment]
JFYI 

this works in the latest versions

```yaml
          filters:
            - member: country
              operator: in
              values: "{ securityContext.countries }"
```

but this - does not 


```yaml
          filters:
            - member: country
              operator: in
              values: { securityContext.countries }
```

**Comment by eshepelyuk** [comment]
> Both are incorrect. You should pass an array in `values`: https://cube.dev/docs/product/data-modeling/reference/data-access-policies#row_level

No, it won't work in case the security context parameter is array/list  (as this entire issue is all about)

The following access policy 

```yaml
cubes:
  - name: customers
    sql_table: public.customer
    access_policy:
      - role: "*"
        row_level:
          filters:
            - member: country
              operator: in
              values: [ "{ securityContext.countries }" ]
```

will result into such query filter, that apparently incorrect 

```json
{
  "filters": [
    {"member": "customers.country", "operator": "in", "values": ["Germany,United States"]}
  ]
}
```
