### ISSUE TITLE
dockercompose - MinIO with duckdb on Cube

### ISSUE THREAD

**Issue by ClorisYT** [cube-js/cube#9273]
I encountered an issue deploying the Cube.js service using Docker Compose on a virtual machine (VM). The service fails to start correctly, and no error logs indicate the root cause of the failure.

Environment Details:
Service: Cube.js (cubejs/cube:latest)
Environment: Virtual Machine (VM)

```yaml
services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4001:4000

    environment:
      - CUBEJS_DEV_MODE=true
      - CUBESQL_SQL_PUSH_DOWN=true
      - CUBEJS_EXTERNAL_DEFAULT=true
      - CUBESTORE_MINIO_ACCESS_KEY_ID=<id>
      - CUBESTORE_MINIO_BUCKET=try
      - CUBESTORE_MINIO_REGION=us-east-1
      - CUBESTORE_MINIO_SECRET_ACCESS_KEY=<key>
      - CUBESTORE_MINIO_SERVER_ENDPOINT=http://xxx.xx.xxx:9009  
      - CUBEJS_DB_TYPE=duckdb

      # - CUBEJS_DB_DUCKDB_DATABASE_PATH=':memory:'
    volumes:
      - ./cubestore:/cube/data

```

So I need someone to help me deal with it or advise me. Thank you.
