### ISSUE TITLE
Error when filtering a view by a multi_stage measure

### ISSUE THREAD

**Issue by victormorenoi** [cube-js/cube#9314]
**Describe the bug**
When executing a query on the `mart_media` view with `multi_stage=true` measures, I encounter an error, although the same query works correctly when run on the `mart_media_base` cube. 
Specifically, the measure `brand_name_filter`, which is defined as `multi_stage=true`, causes the error in the view. However, the `count_total` measure, which is also defined as `multi_stage=true`, works fine. 
Both measures work correctly if the data is queried from the cube instead of the view.

**To Reproduce**
- Define a cube `test_cube` with the provided schema.
- Create a view `test_cube_view` that joins the `test_cube` cube.
- Run a query involving the `brand_name_filter` and `count_total` measures in the view.
- Observe that the `count_total` measure works fine, but the `brand_name_filter` measure fails with an error.

**Expected behavior**
The `brand_name_filter` measure (with `multi_stage=true`) should work correctly when queried from the view, similar to how the `count_total` measure works.

**Screenshots**

![Image](https://github.com/user-attachments/assets/94a6b29b-1308-44b3-a8c5-bd567dd12d98)

**Minimally reproducible Cube Schema**
CUBE
```
cubes:
  - name: test_cube
    sql_table: data_table

    dimensions:

      - name: unique_key
        sql: "{CUBE}.\"UNIQUE_KEY\""
        type: string
        primary_key: true
     
      - name: brand_name
        sql: "{CUBE}.\"BRAND_NAME\""
        type: string

      - name: retailer_name
        sql: "{CUBE}.\"RETAILER_NAME\""
        type: string
      
      - name: datagroup_id
        sql: "{CUBE}.\"DATAGROUP_ID\""
        type: string
      
      - name: date
        sql: "{CUBE}.\"DATE\""
        type: time
      
      - name: multibrand_weight
        sql: "{CUBE}.\"MULTIBRAND_WEIGHT\""
        type: number

      - name: category_name
        sql: "{CUBE}.\"NAME\""
        type: string

    measures:

      - name: brand_name_filter
        type: string
        multi_stage: true
        sql: brand_name

      - name: count
        type: sum
        sql: multibrand_weight

      - name: count_total
        type: sum
        multi_stage: true
        sql: "{count}"
        group_by:
          - retailer_name
          - category_name

      - name: share
        sql: "{count} * 100 / {count_total}"
        type: number
        format: percent

    access_policy:

      - role: client_user
        member_level:
          includes: "*"
        row_level:
          filters:
            - member: datagroup_id
              operator: equals
              values: [ "{ securityContext.datagroup_id }" ]
```

VIEW
```
views:
  
  - name: test_cube_view

    cubes:
      - join_path: test_cube
        includes: "*"
```

**Version:**
latest (1.2.17)

**Additional context**
The issue only arises when querying the measures from the view `test_cube_view`, specifically with the `brand_name_filter` measure (defined as `multi_stage=true`). The same query works as expected when queried from the cube `test_cube`.

**Comment by igorlukanin** [comment]
Thanks for the report — I dug into this, and the root cause is that `brand_name_filter` is **not a valid multi-stage measure**.

A `multi_stage: true` measure is meant to compute over the result of other measures across a `group_by` partition (a windowed/second-pass aggregation). `brand_name_filter` instead just wraps a dimension (`sql: brand_name`) with no `group_by` and references no other measures, so there is nothing for the multi-stage pass to compute. The legacy SQL planner happens to tolerate this when you query the cube directly, but on the **view** path it produces a broken inner query — hence the confusing error you saw.

The new (Tesseract) SQL planner validates this consistently and rejects the measure on **both** the cube and the view with a clearer message:

```
Multi stage member 'test_cube.brand_name_filter' doesn't reference other members.
```

### What to do instead

If you just want to filter or group by the brand name, it's a **dimension**, not a measure — use `brand_name` directly (it already exists in your model). No multi-stage measure is needed:

```yaml
filters:
  - member: test_cube_view.brand_name
    operator: equals
    values: ["..."]
```

Multi-stage measures should reference other measures and define a `group_by` partition, the way your `count_total` does — which is exactly why `count_total` works through the view and `brand_name_filter` does not.

Closing as the measure definition is the issue. If you have a use case where `brand_name_filter` was meant to do something a plain dimension can't, let us know what the intended computation is and we'll be glad to help model it.
