### ISSUE TITLE
Can't use set and notSet in access policy filters

### ISSUE THREAD

**Issue by tagspace** [cube-js/cube#9348]
**Describe the bug**
Can't use `set` or `notSet` operator in row level filters in access policies.

**To Reproduce**

Create a model like so:

```
cubes:
  - name: customers
    sql_table: public.customers

    access_policy:
      - role: "admin"
        row_level:
          filters:
            - member: email
              operator: set
              values: []
```

You'll get error:
`accessPolicy[0].rowLevel.filters[0] = [object Object] does not match any of the allowed types`

**Expected behavior**
Should be able to use all filter operators in access policies.

**Screenshots**
https://files.slack.com/files-pri/TC0C1HURK-F08HGL9CF7S/screenshot_2025-03-08_at_09.30.16.png

**Version:**
Cube cloud
