### ISSUE TITLE
Different query in views tham

### ISSUE THREAD

**Issue by victormorenoi** [cube-js/cube#9359]
**Describe the bug**
When querying a `view`, the generated SQL query is different from the one generated when querying the corresponding `cube`. **This difference causes the query to fail for the cube but work correctly for the view.**

The issue occurs when selecting a dimension and two measures, one of which is `multi-stage`, while filtering by the multi-stage measure included in the select.

**To Reproduce**
1. Create a measure with multi-stage ranking:
```
- name: rank_price_avg_by_retailer
  sql: "rank() over (partition by {retailer_name} order by {pp_price_avg} desc)"
  type: number   
  multi_stage: true
```
2. Run a query selecting a dimension and two measures, filtering by `rank_price_avg_by_retailer`.
3. Compare the generated SQL query for the **cube** vs. the **view**.
4. The cube-generated query fails with an SQL compilation error.

**Expected behavior**
The query generated for the Cube should match the one generated for the View or at least be structured in a way that does not cause an error.

**Screenshots**
The REST-API is the same, changing `mart_daily_plp_ai_view` by `mart_daily_plp` (cube name).

<img width="614" alt="Image" src="https://github.com/user-attachments/assets/5389910a-9819-4837-bf03-ee52ae2d0fed" />

**Minimally reproducible Cube Schema**

```
cubes:
  - name: mart_daily_plp
    sql_table: MART_DAILY_PLP
    dimensions:
      - name: brand_name
        sql: "{CUBE}.BRAND_NAME"
        type: string
      - name: price
        sql: "case when {CUBE}.PRICE <= 0 then null else {CUBE}.PRICE end"
        type: number

    measures:
      - name: pp_price_avg
        title: "Average Price"
        description: "Average price of all offers"
        sql: "{price}"
        type: avg       
        filters: 
          - sql: "{price} is not null"
      - name: rank_price_avg_by_retailer
        sql: "rank() over (partition by {retailer_name} order by {pp_price_avg} desc)"
        type: number   
        multi_stage: true
```

```
views:

  - name: mart_daily_plp_ai_view
    cubes:
      - join_path: mart_daily_plp
        includes: "*"
```

**Version:**
Last Version 1.2.23

**Additional context**

**Comment by igorlukanin** [comment]
Thanks for the report! The root cause here is the way the multi-stage measure is defined rather than the cube-vs-view path itself.

`rank_price_avg_by_retailer` is written as a raw window function:

```yaml
- name: rank_price_avg_by_retailer
  sql: "rank() over (partition by {retailer_name} order by {pp_price_avg} desc)"
  type: number
  multi_stage: true
```

This isn't the supported way to define a ranking multi-stage measure. Multi-stage rank measures should be declared with `type: rank` plus `order_by`, and the partition is controlled by `group_by` / `reduce_by` — Cube then generates the `rank() OVER (...)` itself and places it in the correct CTE. With the raw form above, the `{retailer_name}` reference isn't rewritten to the projected alias, so the generated SQL leaks the bare `mart_daily_plp.RETAILER_NAME` identifier into a scope where it doesn't exist (hence `invalid identifier`).

The equivalent of your `partition by {retailer_name}` is **`group_by`**:

```yaml
- name: rank_price_avg_by_retailer
  multi_stage: true
  type: rank
  order_by:
    - sql: "{pp_price_avg}"
      dir: desc
  group_by:
    - retailer_name
```

This generates `rank() OVER (PARTITION BY retailer_name ORDER BY pp_price_avg DESC)` and works on both the cube and the view.

One thing to watch out for: the ranking example in the docs uses `reduce_by`, which behaves differently from `group_by`. `group_by` sets the partition directly (absolute), whereas `reduce_by` *removes* dimensions from the query's selection before the window stage, so the partition becomes `(selected dimensions − reduce_by)`. For "rank within retailer" you want `group_by: retailer_name`; `reduce_by: retailer_name` would partition by the other selected dimension and silently give different results.

Docs: https://cube.dev/docs/product/data-modeling/concepts/multi-stage-calculations

Closing this as the modeling question is resolved.
