### ISSUE TITLE
Rolling windows for clickhouse

### ISSUE THREAD

**Issue by mjvankampen** [cube-js/cube#9600]
**Is your feature request related to a problem? Please describe.**
I want to use rolling windows in clickhouse but I cannot get them to work when applying a granularity. Looking at the tests running for clickhouse I guess this is not supported?

**Describe the solution you'd like**
Rolling windows work with granularity applied.

**Describe alternatives you've considered**
At least document that it is not supported so people don't lose time. Perhaps include an alternative.

**Additional context**

**Comment by igorlukanin** [comment]
@mjvankampen Does it not work for you only with any granularity or only with custom granularities?

**Comment by mjvankampen** [comment]
For example using the example from the [docs](https://cube.dev/docs/product/data-modeling/concepts/multi-stage-calculations#rolling-window) with the query used there (I did add a date range) I get the following error:

<img width="1210" alt="Image" src="https://github.com/user-attachments/assets/7bded33a-384a-4e7f-a2ce-48645d2f059c" />

```yaml
cubes:
  - name: orders
    sql: >
      SELECT 1 AS id, '2025-01-01'::TIMESTAMP AS time UNION ALL
      SELECT 2 AS id, '2025-01-11'::TIMESTAMP AS time UNION ALL
      SELECT 3 AS id, '2025-01-21'::TIMESTAMP AS time UNION ALL
      SELECT 4 AS id, '2025-01-31'::TIMESTAMP AS time UNION ALL
      SELECT 5 AS id, '2025-02-01'::TIMESTAMP AS time UNION ALL
      SELECT 6 AS id, '2025-02-11'::TIMESTAMP AS time UNION ALL
      SELECT 7 AS id, '2025-02-21'::TIMESTAMP AS time UNION ALL
      SELECT 8 AS id, '2025-03-01'::TIMESTAMP AS time UNION ALL
      SELECT 9 AS id, '2025-03-11'::TIMESTAMP AS time UNION ALL
      SELECT 10 AS id, '2025-03-21'::TIMESTAMP AS time UNION ALL
      SELECT 11 AS id, '2025-03-31'::TIMESTAMP AS time UNION ALL
      SELECT 12 AS id, '2025-04-01'::TIMESTAMP AS time
 
    dimensions:
      - name: time
        sql: time
        type: time
 
    measures:
      - name: rolling_count_month
        sql: id
        type: count
        rolling_window:
          trailing: unbounded
```
