### ISSUE TITLE
contextToRoles does not work since 1.3.0

### ISSUE THREAD

**Issue by mironovich** [cube-js/cube#9626]
**Describe the bug**
Method described in cube.js for contextToRoles is not executed.

**To Reproduce**
1. simply paste in cube.js
```js
  contextToRoles: () => {
    console.log('== contextToRoles()')
    return ['default']
  },

  contextToAppId: () => {
    console.log('== contextToAppId() ')
    return 'default'
  },
```
2. make request in playground (tried also for cube with access_policy)
3. console only has `== contextToAppId()`

**Expected behavior**
Console should also have `== contextToRoles()`

**Version:**
[1.3.0]

**Additional context**
Same access policies work in version 1.2.34 and before, and stopped working since 1.3.0.
example with console.log is easier to reproduce

**Comment by igorlukanin** [comment]
I've tried to reproduce this with the following setup:


```yaml
# docker-compose.yml
services:
  cube:
    image: cubejs/cube:v1.3.22
    ports:
      - 4000:4000
      - 15432:15432
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_TYPE=duckdb
    volumes:
      - .:/cube/conf
```

```javascript
// cube.js
module.exports = {
  contextToRoles: () => {
    console.log('== contextToRoles()')
    return ['default']
  },

  contextToAppId: () => {
    console.log('== contextToAppId() ')
    return 'default'
  },
}
```

```yaml
// model/dap.yml
cubes:
  - name: dap
    sql: SELECT 123

    measures:
      - name: count
        type: count
        
    access_policy:
      - role: "*"
        member_level:
          includes: []
        row_level:
          filters:
            - member: count
              operator: equals
              values: [ "123" ]
```

It looks like access policies work as they should:
* Member-level controls apply: you can see the "lock" icon on the member
* Row-level controls apply as well: you can see the filter in the generated SQL

<img width="1394" alt="Image" src="https://github.com/user-attachments/assets/f3d7a912-9fe1-42ed-8235-9f31e07535bc" />

Also, logging from `contextToRoles` can be seen in the console.

<img width="1394" alt="Image" src="https://github.com/user-attachments/assets/a26ec979-b835-4e8c-8bfd-8adce6b2ab20" />

@mironovich Can you please check if the issue reproduces for you with this config? If it does not, what's different in your configuration?
