### ISSUE TITLE
Unable to connect Cube Core from BI system.

### ISSUE THREAD

**Issue by szahorodnii** [cube-js/cube#9730]
We make a local deployment of Cube Core in DEV mode.
Input data: AWS EC2, Docker compose, Databricks(data source), S3 (store Data Model).

--------------- Docker compose--------------
```
serices:
  cube_api:
    restart: always
    build:
      context: ./cube_api
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: AKIA*********************************
      AWS_SECRET_ACCESS_KEY: **********************************
      AWS_REGION: us-east-1
      CUBEJS_AWS_SECRET: **********************************
      CUBEJS_AWS_REGION: us-east-1
      CUBEJS_AWS_KEY: AKIA*********************************
      CUBEJS_S3_MODELS_BUCKET: s3-data-cube
      CUBEJS_S3_MODELS_PREFIX: models/
      CUBEJS_S3_MODELS_VERSION_KEY: models/version.json
      CUBEJS_CUBESTORE_HOST: cubestore_router
      RUST_BACKTRACE: full
      CUBEJS_DB_DATABRICKS_CATALOG: workspace
      CUBEJS_DB_EXPORT_BUCKET_AWS_SECRET: **********************************
      CUBEJS_DB_EXPORT_BUCKET_TYPE: s3
      CUBEJS_DB_EXPORT_BUCKET_AWS_REGION: us-east-1
      CUBEJS_DB_DATABRICKS_ACCEPT_POLICY: true
      CUBEJS_DB_EXPORT_BUCKET: s3://s3-data-cube
      CUBEJS_DEV_MODE: true
      CUBEJS_DB_USER: token
      CUBEJS_DB_DATABRICKS_URL: jdbc:databricks://dbc-********************.cloud.databricks.com:443;transportMode=http;ssl=1;httpPath=/sql/1.0/warehouses/********************;AuthMech=3
      CUBEJS_DB_NAME: gold
      CUBEJS_DB_TYPE: databricks-jdbc
      CUBEJS_DB_DATABRICKS_TOKEN: ********************
      CUBEJS_DB_EXPORT_BUCKET_AWS_KEY: AKIA*********************************
      CUBEJS_PG_SQL_PORT: 15432
      CUBEJS_SQL_USER: cubeuser
      CUBEJS_SQL_PASSWORD: pass2025
      CUBEJS_DB_LOG: true
      CUBEJS_LOG_LEVEL: trace
    ports:
      - 4000:4000
      - 15432:15432
    volumes:
      - ./cube.js:/cube/conf/cube.js
    depends_on:
      - cube_refresh_worker
      - cubestore_router
      - cubestore_worker_1
    networks:
      - cube-network
  cube_refresh_worker:
    restart: always
    build:
      context: ./cube_refresh_worker
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: AKIA*********************************
      AWS_SECRET_ACCESS_KEY: **********************************
      AWS_REGION: us-east-1
      CUBEJS_AWS_SECRET: **********************************
      CUBEJS_AWS_REGION: us-east-1
      CUBEJS_AWS_KEY: AKIA*********************************
# S3 Bucket Configuration
      CUBEJS_S3_MODELS_BUCKET: s3-data-cube
      CUBEJS_S3_MODELS_PREFIX: models/
      CUBEJS_S3_MODELS_VERSION_KEY: models/version.json     
      RUST_BACKTRACE: full
      CUBEJS_DB_DATABRICKS_CATALOG: workspace
      PORT: 4001
      CUBEJS_DB_DATABRICKS_ACCEPT_POLICY: true
      CUBEJS_DEV_MODE: true
      CUBEJS_DB_USER: token
      CUBEJS_CUBESTORE_HOST: cubestore_router
      CUBEJS_DB_DATABRICKS_URL: jdbc:databricks://dbc-********************.cloud.databricks.com:443;transportMode=http;ssl=1;httpPath=/sql/1.0/warehouses/********************;AuthMech=3
      CUBEJS_DB_NAME: gold
      CUBEJS_REFRESH_WORKER: true
      CUBEJS_DB_TYPE: databricks-jdbc
      CUBEJS_DB_DATABRICKS_TOKEN: ********************
      CUBEJS_DB_LOG: true
      CUBEJS_LOG_LEVEL: trace
    volumes:
      - ./cube.js:/cube/conf/cube.js
    depends_on:
      - cubestore_router
      - cubestore_worker_1
    networks:
      - cube-network
  cubestore_router:
    build:
      context: ./cubestore_router
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: AKIA*********************************
      AWS_SECRET_ACCESS_KEY: **********************************
      AWS_REGION: us-east-1
      CUBESTORE_S3_SUB_PATH: cubestore-data-router
      RUST_BACKTRACE: full
      CUBESTORE_S3_BUCKET: s3-data-cube
      CUBESTORE_META_PORT: 9999
      CUBESTORE_AWS_ACCESS_KEY_ID: AKIA*********************************
      CUBESTORE_WORKERS: cubestore_worker_1:10001
      CUBESTORE_AWS_SECRET_ACCESS_KEY: **********************************
      CUBESTORE_SERVER_NAME: cubestore_router:9999
      CUBEJS_DB_EXPORT_BUCKET_AWS_KEY: AKIA*********************************
      CUBESTORE_S3_REGION: us-east-1
      CUBEJS_LOG_FORMAT: json
    ports:
      - 3030:3030
      - 9999:9999
    volumes:
      - cubestore-data:/cube/data
    networks:
      - cube-network
  cubestore_worker_1:
    build:
      context: ./cubestore_worker
      dockerfile: Dockerfile
    environment:
      CUBEJS_PRE_AGGREGATIONS_SCHEMA: dev_pre_aggregations
      AWS_ACCESS_KEY_ID: AKIA*********************************
      AWS_SECRET_ACCESS_KEY: **********************************
      AWS_REGION: us-east-1
      CUBESTORE_S3_SUB_PATH: cubestore-data-worker
      RUST_BACKTRACE: full
      CUBESTORE_AWS_ACCESS_KEY_ID: AKIA*********************************
      CUBESTORE_WORKERS: cubestore_worker_1:10001
      CUBESTORE_META_ADDR: cubestore_router:9999
      CUBESTORE_S3_BUCKET: s3-data-cube
      CUBESTORE_AWS_SECRET_ACCESS_KEY: **********************************
      CUBESTORE_SERVER_NAME: cubestore_worker_1:10001
      CUBESTORE_WORKER_PORT: 10001
      CUBESTORE_S3_REGION: us-east-1
      CUBEJS_LOG_FORMAT: json
    depends_on:
      - cubestore_router
    ports:
      - 10001:10001
    volumes:
      - cubestore-data:/cube/data
    networks:
      - cube-network
volumes:
  cubestore-data:
networks:
  cube-network:
    driver: bridge

```

--------- cube_api Dockerfile-------

```
FROM cubejs/cube:jdk as builder

USER root
RUN apt-get update && \
    apt-get install -y unzip curl && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf awscliv2.zip aws && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

FROM cubejs/cube:jdk
COPY --from=builder /usr/local/aws-cli /usr/local/aws-cli
RUN ln -s /usr/local/aws-cli/v2/current/bin/aws /usr/local/bin/aws

RUN npm install aws-sdk

USER cube

WORKDIR /cube/conf
```

Cube Core works well.
The attempt to connect to Cube from BI system(sisense.com) through PostgreSQL driver fails -  Connection failed: Authentication
Authentication parameters are correct. How to identify the error reason?
